// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests
import * as loaders_environment from "./loaders/environment";
import * as loaders_fonts_googleFonts from "./loaders/fonts/googleFonts";
import * as loaders_fonts_local from "./loaders/fonts/local";
import * as loaders_secret from "./loaders/secret";
import * as loaders_secretString from "./loaders/secretString";

const sections_Analytics_Analytics = () => import("./sections/Analytics/Analytics");
const sections_Seo_Seo = () => import("./sections/Seo/Seo");
const sections_Seo_SeoV2 = () => import("./sections/Seo/SeoV2");

const manifest = {
	name: "website",
	loaders: {
		"website/loaders/environment": loaders_environment,
		"website/loaders/fonts/googleFonts": loaders_fonts_googleFonts,
		"website/loaders/fonts/local": loaders_fonts_local,
		"website/loaders/secret": loaders_secret,
		"website/loaders/secretString": loaders_secretString,
	},
	actions: {},
	sections: {
		"website/sections/Analytics/Analytics": sections_Analytics_Analytics,
		"website/sections/Seo/Seo": sections_Seo_Seo,
		"website/sections/Seo/SeoV2": sections_Seo_SeoV2,
	},
} as const;

export type Manifest = typeof manifest;
export default manifest;
