// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests
import * as actions_send from "./actions/send";

const manifest = {
	name: "resend",
	loaders: {},
	actions: {
		"resend/actions/send": actions_send,
	},
	sections: {},
} as const;

export type Manifest = typeof manifest;
export default manifest;
