// @vitest-environment node
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it } from "vitest";
import { LEGACY_ALIASES } from "./builtins";
import {
  computeRevision,
  content,
  readSavedBlocks,
  renderContentModule,
  writeContent,
} from "./content";
import { decoPaths } from "./root";
import { createFixture, type Fixture, recorder } from "./__tests__/fixture";

let fixture: Fixture;
afterEach(() => fixture?.remove());

const home = { __resolveType: "page", name: "Home", path: "/", sections: [] };

describe("reading .deco/blocks", () => {
  it("reads one entry per JSON file, named by the file-name rule", () => {
    fixture = createFixture({
      ".deco/blocks/HomePage.json": home,
      ".deco/blocks/collections%2Fblog%2Fposts%2Fabc.json": { __resolveType: "post" },
      ".deco/blocks/notes.txt": "ignored",
    });
    const saved = readSavedBlocks(decoPaths(fixture.root).blocks);
    expect(Object.keys(saved.blocks).sort()).toEqual(["HomePage", "collections/blog/posts/abc"]);
    expect(saved.files["collections/blog/posts/abc"]).toBe("collections%2Fblog%2Fposts%2Fabc.json");
    expect(saved.diagnostics).toEqual([]);
  });

  it("is empty without a blocks folder", () => {
    fixture = createFixture();
    fs.rmSync(path.join(fixture.root, ".deco/blocks"), { recursive: true });
    expect(readSavedBlocks(decoPaths(fixture.root).blocks).blocks).toEqual({});
  });

  it("reports invalid JSON and non-object files as errors", () => {
    fixture = createFixture({
      ".deco/blocks/Broken.json": "{ nope",
      ".deco/blocks/List.json": "[1, 2]",
    });
    const saved = readSavedBlocks(decoPaths(fixture.root).blocks);
    expect(saved.blocks).toEqual({});
    expect(saved.diagnostics.map((d) => [d.file, d.severity])).toEqual([
      ["Broken.json", "error"],
      ["List.json", "error"],
    ]);
  });

  it("keeps one spelling of a name and reports the others", () => {
    fixture = createFixture({
      ".deco/blocks/pages-Home%20Page.json": { __resolveType: "page", name: "old", path: "" },
      ".deco/blocks/pages-Home%2520Page.json": {
        __resolveType: "page",
        name: "new",
        path: "/home",
      },
    });
    const saved = readSavedBlocks(decoPaths(fixture.root).blocks);
    // The entry with a path wins; its name is its file name decoded once.
    expect(Object.keys(saved.blocks)).toEqual(["pages-Home%20Page"]);
    expect(saved.blocks["pages-Home%20Page"].name).toBe("new");
    expect(saved.diagnostics).toEqual([
      {
        file: "pages-Home%20Page.json",
        severity: "warning",
        message: 'another spelling of "pages-Home%20Page"; pages-Home%2520Page.json wins',
      },
    ]);
  });

  it("reports subfolders, which aren't read", () => {
    fixture = createFixture({ ".deco/blocks/nested/A.json": home });
    const saved = readSavedBlocks(decoPaths(fixture.root).blocks);
    expect(saved.blocks).toEqual({});
    expect(saved.diagnostics[0]).toMatchObject({ file: "nested", severity: "warning" });
  });
});

describe("the revision", () => {
  it("is a hash of the whole map, independent of key order", () => {
    const a = computeRevision({ A: { x: 1, y: [1, { b: 2, a: 1 }] }, B: {} });
    const b = computeRevision({ B: {}, A: { y: [1, { a: 1, b: 2 }], x: 1 } });
    expect(a).toBe(b);
    expect(a).toMatch(/^[0-9a-f]{64}$/);
  });

  it("changes when any entry changes", () => {
    const a = computeRevision({ A: { x: 1 } });
    expect(computeRevision({ A: { x: 2 } })).not.toBe(a);
    expect(computeRevision({ A: { x: 1 }, B: {} })).not.toBe(a);
    expect(computeRevision({ a: { x: 1 } })).not.toBe(a);
  });
});

describe("the content module", () => {
  it("imports each JSON file and exports { revision, blocks, aliases }", () => {
    fixture = createFixture({ ".deco/blocks/HomePage.json": home });
    const source = renderContentModule(readSavedBlocks(decoPaths(fixture.root).blocks));
    expect(source.startsWith("// Generated by deco content; don't edit.\n")).toBe(true);
    expect(source).toContain(
      'import HomePage from "./blocks/HomePage.json" with { type: "json" };',
    );
    expect(source).toContain(`revision: "${computeRevision({ HomePage: home })}"`);
    expect(source).toContain('"HomePage": HomePage,');
    expect(source).toContain('"website/pages/Page.tsx": "page",');
    expect(source).toContain("export default content;");
  });

  it("inlines files whose names aren't portable import paths", () => {
    fixture = createFixture({
      ".deco/blocks/pages-Home%2520Page.json": home,
      ".deco/blocks/default.json": { __resolveType: "x" },
      ".deco/blocks/1st.json": { __resolveType: "x" },
    });
    const source = renderContentModule(readSavedBlocks(decoPaths(fixture.root).blocks));
    expect(source).not.toContain('pages-Home%2520Page.json" with');
    expect(source).toContain(`"pages-Home%20Page": ${JSON.stringify(home)},`);
    // Reserved words and leading digits get safe identifiers.
    expect(source).toContain('import _default from "./blocks/default.json"');
    expect(source).toContain('import _1st from "./blocks/1st.json"');
  });

  it("loads in a real module system with the same content and revision", async () => {
    fixture = createFixture({
      ".deco/blocks/HomePage.json": home,
      ".deco/blocks/pages-Home%2520Page.json": home,
    });
    const result = writeContent(decoPaths(fixture.root));
    const mod = await import(/* @vite-ignore */ pathToFileURL(result.file).href);
    expect(mod.default.blocks).toEqual({ HomePage: home, "pages-Home%20Page": home });
    expect(mod.default.revision).toBe(computeRevision(mod.default.blocks));
    expect(mod.default.aliases).toEqual(LEGACY_ALIASES);
  });

  it("only rewrites the file when it changes", () => {
    fixture = createFixture({ ".deco/blocks/HomePage.json": home });
    const paths = decoPaths(fixture.root);
    expect(writeContent(paths).changed).toBe(true);
    expect(writeContent(paths).changed).toBe(false);
    fixture.write(".deco/blocks/Other.json", {
      __resolveType: "page",
      name: "O",
      path: "/o",
      sections: [],
    });
    expect(writeContent(paths).changed).toBe(true);
  });

  it("refuses to write a module from unreadable content", () => {
    fixture = createFixture({ ".deco/blocks/Broken.json": "{" });
    expect(() => writeContent(decoPaths(fixture.root))).toThrow(/Broken\.json: invalid JSON/);
  });

  it("deco content prints what it wrote, and never reads the block map", () => {
    fixture = createFixture({
      ".deco/blocks/HomePage.json": home,
      ".deco/index.ts": "this is not valid TypeScript (",
    });
    const out = recorder();
    expect(content({ cwd: path.join(fixture.root, "src"), reporter: out })).toBe(0);
    expect(out.text()).toMatch(
      /^wrote \.deco\/blocks\.gen\.ts \(1 blocks, revision [0-9a-f]{12}\)$/,
    );
    expect(fixture.exists(".deco/blocks.gen.ts")).toBe(true);
  });
});
