/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionIndexRouteImport } from './routes/$version/index'
import { Route as VersionSlugRouteImport } from './routes/$version/$slug'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap/index'
import { Route as RoadmapSectionRouteImport } from './routes/roadmap/$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionIndexRoute = VersionIndexRouteImport.update({
  id: '/$version/',
  path: '/$version/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionSlugRoute = VersionSlugRouteImport.update({
  id: '/$version/$slug',
  path: '/$version/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapSectionRoute = RoadmapSectionRouteImport.update({
  id: '/roadmap/$section',
  path: '/roadmap/$section',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$version/$slug': typeof VersionSlugRoute
  '/roadmap/$section': typeof RoadmapSectionRoute
  '/$version/': typeof VersionIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$version/$slug': typeof VersionSlugRoute
  '/roadmap/$section': typeof RoadmapSectionRoute
  '/$version': typeof VersionIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$version/$slug': typeof VersionSlugRoute
  '/roadmap/$section': typeof RoadmapSectionRoute
  '/$version/': typeof VersionIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$version/$slug' | '/roadmap/$section' | '/$version/' | '/roadmap/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$version/$slug' | '/roadmap/$section' | '/$version' | '/roadmap'
  id:
    | '__root__'
    | '/'
    | '/$version/$slug'
    | '/roadmap/$section'
    | '/$version/'
    | '/roadmap/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VersionSlugRoute: typeof VersionSlugRoute
  RoadmapSectionRoute: typeof RoadmapSectionRoute
  VersionIndexRoute: typeof VersionIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$version/': {
      id: '/$version/'
      path: '/$version'
      fullPath: '/$version/'
      preLoaderRoute: typeof VersionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$version/$slug': {
      id: '/$version/$slug'
      path: '/$version/$slug'
      fullPath: '/$version/$slug'
      preLoaderRoute: typeof VersionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$section': {
      id: '/roadmap/$section'
      path: '/roadmap/$section'
      fullPath: '/roadmap/$section'
      preLoaderRoute: typeof RoadmapSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VersionSlugRoute: VersionSlugRoute,
  RoadmapSectionRoute: RoadmapSectionRoute,
  VersionIndexRoute: VersionIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
