/**
 * Content: the next major reads saved blocks only from `.deco/blocks`, one
 * JSON file per entry, named by the protocol's file-name rule
 * (`@decocms/blocks/protocol/keys`). A v7 site that has them there keeps
 * them as they are; one that only has a decofile (the `/.decofile` dump, or
 * the generated `.deco/blocks.gen.json`) gets it split into files. The v7
 * generated files in `.deco/` go: `deco schema` and `deco content` write
 * their replacements.
 */
import fs from "node:fs";
import path from "node:path";
import { blockFileName, checkBlockName, serializeBlock } from "@decocms/blocks/protocol/keys";
import type { Report } from "./report";
import { isPlainObject, readContent } from "./walk";

/** Generated by the v7 codegen; nothing in the next major reads them. */
const V7_GENERATED = [
  "blocks.gen.json",
  "blocks.gen.ts",
  "loaders.gen.ts",
  "sections.gen.ts",
  "meta.gen.json",
];

/** Where a v7 site may keep a whole decofile, tried in order. */
const DECOFILE_CANDIDATES = [".deco/blocks.gen.json", ".decofile.json", ".decofile"];

function hasJsonFiles(dir: string): boolean {
  try {
    return fs.readdirSync(dir).some((f) => f.endsWith(".json"));
  } catch {
    return false;
  }
}

/**
 * The entries of a decofile: a map of entry name to block, either at the top
 * level or under `blocks` (the shape `/.decofile` serves).
 */
export function decofileEntries(decofile: unknown): Record<string, Record<string, unknown>> {
  if (!isPlainObject(decofile)) return {};
  const values = Object.values(decofile);
  const flat = values.length > 0 && values.every((v) => isPlainObject(v) && "__resolveType" in v);
  const map = flat ? decofile : isPlainObject(decofile.blocks) ? decofile.blocks : {};
  const entries: Record<string, Record<string, unknown>> = {};
  for (const [name, block] of Object.entries(map)) {
    if (isPlainObject(block)) entries[name] = block;
  }
  return entries;
}

interface MoveContentOptions {
  /** A decofile to split into `.deco/blocks`, relative to the root. */
  decofile?: string;
}

export function moveContent(root: string, report: Report, options: MoveContentOptions = {}): void {
  const blocksDir = path.join(root, ".deco", "blocks");
  const hasContent = hasJsonFiles(blocksDir);
  if (options.decofile && hasContent) {
    throw new Error(`--decofile given but .deco/blocks already has content`);
  }
  if (!hasContent) {
    const candidates = options.decofile ? [options.decofile] : DECOFILE_CANDIDATES;
    const source = candidates.map((c) => path.resolve(root, c)).find((c) => fs.existsSync(c));
    if (source) {
      const entries = decofileEntries(JSON.parse(fs.readFileSync(source, "utf8")));
      fs.mkdirSync(blocksDir, { recursive: true });
      let written = 0;
      for (const [name, block] of Object.entries(entries)) {
        const [invalid] = checkBlockName(name);
        if (invalid) {
          report.manual.push({
            step: "content",
            subject: name,
            message: `not a valid entry name (${invalid.message}); save it under another name`,
          });
          continue;
        }
        fs.writeFileSync(path.join(blocksDir, blockFileName(name)), serializeBlock(block));
        written++;
      }
      report.done.push({
        step: "content",
        subject: path.relative(root, source),
        message: `split into ${written} files in .deco/blocks`,
      });
    } else if (options.decofile) {
      throw new Error(`no decofile at ${options.decofile}`);
    } else {
      report.manual.push({
        step: "content",
        subject: ".deco/blocks",
        message:
          "no saved blocks found; download the live content (GET <site>/.decofile) and pass it with --decofile",
      });
    }
  }

  // Names the file-name rule rejects (v7 saved editor previews like
  // "Preview site/sections/Hero.tsx"): deco content stops on them.
  for (const d of readContent(root).diagnostics) {
    if (d.severity !== "error") continue;
    report.manual.push({
      step: "content",
      subject: `.deco/blocks/${d.file}`,
      message: `${d.message}, or delete it if nothing references it`,
    });
  }

  for (const file of V7_GENERATED) {
    const full = path.join(root, ".deco", file);
    if (!fs.existsSync(full)) continue;
    fs.rmSync(full);
    report.done.push({
      step: "content",
      subject: `.deco/${file}`,
      message: "removed (v7 generated; deco schema and deco content write the next major's files)",
    });
  }
}
