/**
 * Hand-tokenised code for the landing's mockups (the old landing.html markup, as JSX). The
 * journey panes use the `tk-*` classes, the contract card the `sy-*` classes (legacy.css styles
 * both); the stepper's two code panes keep the Prism token markup the old page produced at runtime
 * (legacy.css `pre .token.*`), frozen here so nothing highlights in the browser.
 */
import type { ReactNode } from 'react'

type C = { children: ReactNode }
export const K = ({ children }: C) => <span className="tk-k">{children}</span>
export const T = ({ children }: C) => <span className="tk-t">{children}</span>
export const P = ({ children }: C) => <span className="tk-p">{children}</span>
export const S = ({ children }: C) => <span className="tk-s">{children}</span>
export const N = ({ children }: C) => <span className="tk-n">{children}</span>
export const F = ({ children }: C) => <span className="tk-f">{children}</span>
export const Cm = ({ children }: C) => <span className="tk-c">{children}</span>
export const Ck = ({ children }: C) => <span className="tk-ck">{children}</span>
/** One numbered line of a `.has-ln` pane. */
export const L = ({ children }: C) => <span className="l">{children}</span>

const tok = (cls: string, text: string) => `<span class="token ${cls}">${text}</span>`
const kw = (t: string) => tok('keyword', t)
const pu = (t: string) => tok('punctuation', t)
const op = (t: string) => tok('operator', t)
const str = (t: string) => tok('string', t)
const cm = (t: string) => tok('comment', t)
const fn = (t: string) => tok('function', t)

/** Step 1 pane (blocks.ts). */
export const STEP1_HTML = [
  cm('// experiments.ts: the function you already have'),
  `${kw('export')} ${kw('default')} ${kw('function')} ${fn('experiments')}${pu('(')}input${op(':')} Experiments${pu(')')} ${pu('{')}`,
  `  ${kw('return')} ${pu('{')} newCheckout${op(':')} ${fn('roll')}${pu('(')}input${pu('.')}newCheckout${pu(')')}${pu(',')} ${cm('/* … */')} ${pu('}')}${pu(';')}`,
  pu('}'),
  '',
  cm('// blocks.ts: give it a name in a block map'),
  `${kw('import')} ${kw('type')} ${pu('{')} Blocks ${pu('}')} ${kw('from')} ${str('"@decocms/blocks"')}${pu(';')}`,
  `${kw('import')} experiments ${kw('from')} ${str('"./experiments"')}${pu(';')}`,
  '',
  `${kw('export')} ${kw('default')} ${pu('{')} experiments ${pu('}')} satisfies Blocks${pu(';')}`,
].join('\n')

/** Step 3 pane (cms.ts). */
export const STEP3_HTML = [
  `${kw('import')} ${pu('{')} createCMS ${pu('}')} ${kw('from')} ${str('"@decocms/blocks"')}${pu(';')}`,
  `${kw('import')} content ${kw('from')} ${str('"./.deco/blocks.gen"')}${pu(';')}`,
  `${kw('import')} blocks ${kw('from')} ${str('"./blocks"')}${pu(';')}`,
  '',
  cm('// .deco/blocks.gen is generated by `deco content`.'),
  cm('// With a token, production reads the hosted Deco CMS;'),
  cm('// without one, it reads that generated module.'),
  `${kw('export')} ${kw('const')} cms ${op('=')} ${fn('createCMS')}${pu('(')}${pu('{')}`,
  `  blocks${pu(',')}`,
  `  content${pu(',')}`,
  `  ${cm("// your site's API key for the hosted Deco CMS")}`,
  `  token${op(':')} process${pu('.')}env${pu('.')}${tok('constant', 'DECO_SITE_TOKEN')}${pu(',')}`,
  `${pu('}')}${pu(')')}${pu(';')}`,
].join('\n')
