// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests

import * as actions_cart_addItems from "./actions/cart/addItems";
import * as actions_cart_updateCoupons from "./actions/cart/updateCoupons";
import * as actions_cart_updateItems from "./actions/cart/updateItems";
import * as actions_user_signIn from "./actions/user/signIn";
import * as actions_user_signUp from "./actions/user/signUp";
import * as loaders_cart from "./loaders/cart";
import * as loaders_ProductDetailsPage from "./loaders/ProductDetailsPage";
import * as loaders_ProductList from "./loaders/ProductList";
import * as loaders_ProductListingPage from "./loaders/ProductListingPage";
import * as loaders_RelatedProducts from "./loaders/RelatedProducts";
import * as loaders_shop from "./loaders/shop";
import * as loaders_user from "./loaders/user";

const manifest = {
	name: "shopify",
	loaders: {
		"shopify/loaders/ProductDetailsPage": loaders_ProductDetailsPage,
		"shopify/loaders/ProductList": loaders_ProductList,
		"shopify/loaders/ProductListingPage": loaders_ProductListingPage,
		"shopify/loaders/RelatedProducts": loaders_RelatedProducts,
		"shopify/loaders/cart": loaders_cart,
		"shopify/loaders/shop": loaders_shop,
		"shopify/loaders/user": loaders_user,
	},
	actions: {
		"shopify/actions/cart/addItems": actions_cart_addItems,
		"shopify/actions/cart/updateCoupons": actions_cart_updateCoupons,
		"shopify/actions/cart/updateItems": actions_cart_updateItems,
		"shopify/actions/user/signIn": actions_user_signIn,
		"shopify/actions/user/signUp": actions_user_signUp,
	},
	sections: {},
} as const;

export type Manifest = typeof manifest;
export default manifest;
