/**
 * CMS Route Helpers
 *
 * Reusable building blocks for CMS catch-all and homepage routes.
 * Since TanStack Router requires routes to be file-based in the site repo,
 * we export helper functions and config that sites use in their route files.
 *
 * @example Site's `src/routes/$.tsx`:
 * ```ts
 * import { createFileRoute, notFound } from "@tanstack/react-router";
 * import { loadCmsPage, cmsRouteConfig } from "@decocms/start/routes";
 * import { DecoPageRenderer } from "@decocms/start/hooks";
 *
 * export const Route = createFileRoute("/$")({
 *   ...cmsRouteConfig({
 *     siteName: "My Store",
 *     defaultTitle: "My Store - Best products",
 *     ignoreSearchParams: ["skuId"],
 *   }),
 * });
 * ```
 */

import type {
  DeferredSection,
  MatcherContext,
  PageSeo,
  ResolvedSection,
} from "@decocms/blocks/cms";
import {
  extractSeoFromProps,
  extractSeoFromSections,
  getDeferredRawProps,
  getDegradedSections,
  getSiteSeo,
  isEagerRequest,
  preloadSectionComponents,
  reExtractRawProps,
  resolveDecoPage,
  resolveDeferredSection,
  resolveDeferredSectionFull,
  runSectionLoaders,
  runSingleSectionLoader,
} from "@decocms/blocks/cms";
import { withTracing } from "@decocms/blocks/middleware/observability";
import {
  type CacheProfileName,
  cacheHeaders,
  detectCacheProfile,
  routeCacheDefaults,
} from "@decocms/blocks/sdk/cacheHeaders";
import { takeExperimentAssignments } from "@decocms/blocks/sdk/experiments";
import {
  parseSegmentCookie,
  SEGMENT_COOKIE,
  type StoredFlag,
  serializeSegmentCookie,
} from "@decocms/blocks/sdk/flags";
import { normalizeUrlsInObject } from "@decocms/blocks/sdk/normalizeUrls";
import { type Device, detectDevice } from "@decocms/blocks/sdk/useDevice";
import { createServerFn } from "@tanstack/react-start";
import {
  getCookies,
  getRequest,
  getRequestHeader,
  getRequestUrl,
  setCookie,
  setResponseHeader,
} from "@tanstack/react-start/server";
import { createElement } from "react";
import { derivePageUrl, isClientNavigation } from "./pageUrl";
import { dedupeGlobals, resolveSiteGlobals } from "./withSiteGlobals";
import type { SiteGlobalRef } from "./withSiteGlobals";

const isServer = typeof document === "undefined";

// Section chunk manifest — maps section keys to chunk filenames.
// Generated by decoVitePlugin's generateBundle hook. Used to emit
// <link rel="modulepreload"> hints for eager sections.
let sectionChunkMap: Record<string, string> = {};

/**
 * Set the section chunk manifest. Called by the site's worker entry
 * or setup after loading the manifest.
 */
export function setSectionChunkMap(map: Record<string, string>): void {
  sectionChunkMap = map;
}

// ---------------------------------------------------------------------------
// Server function — loads a CMS page, runs section loaders, detects cache
// ---------------------------------------------------------------------------

type PageResult = Awaited<ReturnType<typeof loadCmsPageInternal>>;
const pageInflight = new Map<string, Promise<PageResult>>();

/** Same shape as `resolveSiteGlobals()`'s empty result — used when `resolveGlobals: false`. */
const EMPTY_GLOBALS: { resolvedSections: ResolvedSection[]; rawRefs: SiteGlobalRef[] } = {
  resolvedSections: [],
  rawRefs: [],
};

/** One year — the cohort is sticky; the `pct` fingerprint handles re-rolls. */
const SEGMENT_COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

/**
 * Persist sticky A/B decisions recorded during resolution and return them for
 * the client (analytics).
 *
 * Merges the freshly recorded flags over any already in the `deco_segment`
 * cookie (so navigating to a second A/B page doesn't drop the first page's
 * cohort), and only re-issues the cookie when the merged value changed.
 * Setting the cookie also makes the worker skip caching THIS response
 * (`deco_segment` is not a "safe" cookie), so an unassigned visitor never
 * poisons the shared entry — their next request carries the cookie and hits
 * the per-cohort cache entry.
 *
 * `encode: (v) => v` keeps the raw base64 intact — @decocms/apps
 * OneDollarStats reads the cookie with `atob()` directly.
 *
 * Experiment assignments (`sdk/experiments.ts`) merge in through the same
 * writer rather than setting their own cookie — one `deco_segment`, one
 * Set-Cookie. That is why this runs AFTER the section loaders: CMS matchers
 * decide during page resolution, but an experiment is resolved inside a
 * loader, so persisting before the loaders ran would drop the assignment and
 * the visitor would re-roll on every request.
 */
function persistFlags(matcherCtx: MatcherContext, experiments: StoredFlag[] = []): StoredFlag[] {
  const recorded = [...(matcherCtx.flags ?? []), ...experiments];
  if (!recorded.length) return [];

  const raw = matcherCtx.cookies?.[SEGMENT_COOKIE];
  const merged = new Map<string, StoredFlag>();
  for (const f of parseSegmentCookie(raw)) merged.set(f.name, f);
  for (const f of recorded) merged.set(f.name, f);

  const serialized = serializeSegmentCookie([...merged.values()]);
  if (serialized !== (raw ?? "")) {
    setCookie(SEGMENT_COOKIE, serialized, {
      path: "/",
      maxAge: SEGMENT_COOKIE_MAX_AGE,
      sameSite: "lax",
      encode: (v) => v,
    });
  }
  return recorded;
}

/**
 * Run the body sections' loaders and the SEO section's loader in the SAME
 * batch (`Promise.all` via `runSectionLoaders`), instead of sequentially
 * (body first, then `buildPageSeo` separately awaiting the SEO section).
 *
 * On a PDP, the SEO section (e.g. SeoPDP) commonly resolves the same
 * product as a body section via the same commerce loader. Running them
 * sequentially meant the SEO fetch always missed any in-flight request
 * dedup at the fetch-cache layer (apps-vtex's fetchWithCache) — the body
 * fetch had already completed and left the in-flight map by the time the
 * SEO fetch started, so the origin got hit twice per navigation (#355).
 * Batching them gives concurrent identical requests a chance to share one
 * origin round-trip.
 */
/** @internal exported for tests */
export async function runSectionLoadersWithSeo(
  resolvedSections: ResolvedSection[],
  seoSection: ResolvedSection | null | undefined,
  request: Request,
): Promise<{ enrichedSections: ResolvedSection[]; enrichedSeoSection: ResolvedSection | null | undefined }> {
  if (!seoSection) {
    return { enrichedSections: await runSectionLoaders(resolvedSections, request), enrichedSeoSection: seoSection };
  }
  const enrichedAll = await runSectionLoaders([...resolvedSections, seoSection], request);
  return {
    enrichedSections: enrichedAll.slice(0, -1),
    enrichedSeoSection: enrichedAll[enrichedAll.length - 1],
  };
}

async function loadCmsPageInternal(fullPath: string, resolveGlobals: boolean) {
  const [basePath] = fullPath.split("?");
  // On client-side navigation getRequestUrl() is the /_serverFn/... endpoint,
  // not the page being loaded — derivePageUrl rebuilds the real page URL so
  // matcherCtx.url / __pageUrl stay consistent with __pagePath (#280).
  const serverUrl = getRequestUrl();
  const urlWithSearch = derivePageUrl(fullPath, serverUrl);

  const originRequest = getRequest();
  const matcherCtx: MatcherContext = {
    userAgent: getRequestHeader("user-agent") ?? "",
    url: urlWithSearch,
    path: basePath,
    cookies: getCookies(),
    request: originRequest,
    isClientNavigation: isClientNavigation(fullPath, serverUrl),
    flags: [],
  };
  const page = await resolveDecoPage(basePath, matcherCtx);
  if (!page) return null;

  const request = new Request(urlWithSearch, {
    headers: originRequest.headers,
  });

  // Resolve page sections (+ the SEO section, batched together — see #355)
  // and site globals in parallel. Globals are merged into the same
  // `resolvedSections` array so the path through this server function is
  // identical for SSR (F5) and SPA (<Link>) navigations — see #233 for the
  // previous SPA-breakage when `withSiteGlobals` ran client-side and saw an
  // empty client-bundled `blocks.gen.ts`.
  const [{ enrichedSections, enrichedSeoSection }, globals] = await Promise.all([
    runSectionLoadersWithSeo(page.resolvedSections, page.seoSection, request),
    resolveGlobals ? resolveSiteGlobals(matcherCtx) : Promise.resolve(EMPTY_GLOBALS),
  ]);

  // After the loaders — a loader-resolved experiment assignment must be in the
  // cookie this response sets. See persistFlags.
  const flags = persistFlags(matcherCtx, takeExperimentAssignments());

  // Page sections take precedence over globals — dedupe drops any global
  // whose component is already rendered by the page.
  const mergedSections: ResolvedSection[] = [
    ...dedupeGlobals(globals.resolvedSections, enrichedSections),
    ...enrichedSections,
  ];

  // Pre-import eager section modules so their default exports are cached
  // in resolvedComponents. This ensures SSR renders with direct component
  // refs, and the client hydration can skip React.lazy/Suspense.
  const eagerKeys = mergedSections.map((s) => s.component);
  await preloadSectionComponents(eagerKeys);

  const cacheProfile = detectCacheProfile(basePath);
  const ua = getRequestHeader("user-agent") ?? "";
  const device = detectDevice(ua);

  // Build SEO: merge page-level seo block (primary) with section-contributed SEO (secondary)
  const seo = buildPageSeo(
    page.seoSection,
    enrichedSeoSection,
    mergedSections,
    isEagerRequest(matcherCtx),
  );

  // Destructure seoSection out — it's an internal artifact, not serialized to client
  const { seoSection: _seo, ...pageData } = page;

  // Anti-cache-poisoning: if a critical section loader failed, this page is
  // rendering with raw/empty data. Flag the response so the edge refuses to
  // cache the broken 200 and serves stale instead (see workerEntry.ts). Without
  // this, the empty page would be cached as healthy for the whole retention
  // window and stale-if-error would never fire.
  const degraded = getDegradedSections();
  if (degraded.length > 0) {
    setResponseHeader("X-Deco-Degraded", "true");
    console.warn(`[cms] page degraded — critical sections failed: ${degraded.join(", ")}`);
  }

  return {
    ...pageData,
    resolvedSections: normalizeUrlsInObject(mergedSections),
    deferredSections: normalizeUrlsInObject(page.deferredSections),
    cacheProfile,
    degraded: degraded.length > 0,
    pageUrl: urlWithSearch,
    pagePath: basePath,
    seo,
    device,
    flags,
    siteGlobals: { rawRefs: globals.rawRefs },
  };
}

/** Accepted by `loadCmsPage` — a bare path (back-compat) or `{ path, resolveGlobals }`. */
export type LoadCmsPageInput = string | { path: string; resolveGlobals?: boolean };

/** @internal exported for tests */
export function parseLoadCmsPageInput(data: unknown): { path: string; resolveGlobals: boolean } {
  if (typeof data === "string") return { path: data, resolveGlobals: true };
  const obj = data as { path: string; resolveGlobals?: boolean };
  return { path: obj.path, resolveGlobals: obj.resolveGlobals ?? true };
}

export const loadCmsPage = createServerFn({ method: "GET" })
  .inputValidator((data: unknown) => data as LoadCmsPageInput)
  .handler(async (ctx) => {
    const { path: fullPath, resolveGlobals } = parseLoadCmsPageInput(ctx.data);

    // Use the full path (including query string) as the dedup key.
    // Using basePath only caused /s?q=a and /s?q=b to share one promise,
    // returning wrong/empty results for search and filtered PLPs.
    //
    // Client-nav resolves all sections eagerly (#277). An in-flight SSR response
    // for the same path may carry deferredSections; sharing that promise with a
    // concurrent SPA transition would smuggle those deferred sections in, causing
    // loadDeferredSection to run without the per-request commerce app context.
    // Use separate dedup buckets for SSR vs client-nav. `resolveGlobals` is also
    // part of the key — otherwise a `resolveGlobals: false` request could return
    // (or share a promise with) a `resolveGlobals: true` response for the same path.
    const clientNav = isClientNavigation(fullPath, getRequestUrl());
    const inflightKey =
      (clientNav ? `__nav:${fullPath}` : fullPath) + (resolveGlobals ? "" : "|noGlobals");
    const existing = pageInflight.get(inflightKey);
    if (existing) return existing;

    const promise = loadCmsPageInternal(fullPath, resolveGlobals).finally(() =>
      pageInflight.delete(inflightKey),
    );
    pageInflight.set(inflightKey, promise);
    return promise;
  });

/** Accepted by `loadCmsHomePage` — optional so existing no-arg callers keep working. */
export type LoadCmsHomePageInput = { resolveGlobals?: boolean } | undefined;

/** @internal exported for tests */
export function parseLoadCmsHomePageInput(data: unknown): { resolveGlobals: boolean } {
  const obj = (data ?? {}) as { resolveGlobals?: boolean };
  return { resolveGlobals: obj.resolveGlobals ?? true };
}

/**
 * Same as loadCmsPage but hardcoded to "/" path.
 * Avoids passing data through the server function for the homepage.
 */
export const loadCmsHomePage = createServerFn({ method: "GET" })
  .inputValidator((data: unknown) => data as LoadCmsHomePageInput)
  .handler(async (ctx) => {
    const { resolveGlobals } = parseLoadCmsHomePageInput(ctx.data);
    const request = getRequest();
    const ua = getRequestHeader("user-agent") ?? "";
    const serverUrl = getRequestUrl();
    const matcherCtx: MatcherContext = {
      userAgent: ua,
      url: serverUrl.toString(),
      path: "/",
      cookies: getCookies(),
      request,
      isClientNavigation: isClientNavigation("/", serverUrl),
      flags: [],
    };
    const page = await resolveDecoPage("/", matcherCtx);
    if (!page) return null;
    const [{ enrichedSections, enrichedSeoSection }, globals] = await Promise.all([
      runSectionLoadersWithSeo(page.resolvedSections, page.seoSection, request),
      resolveGlobals ? resolveSiteGlobals(matcherCtx) : Promise.resolve(EMPTY_GLOBALS),
    ]);
    const flags = persistFlags(matcherCtx, takeExperimentAssignments());

    const mergedSections: ResolvedSection[] = [
      ...dedupeGlobals(globals.resolvedSections, enrichedSections),
      ...enrichedSections,
    ];

    const eagerKeys = mergedSections.map((s) => s.component);
    await preloadSectionComponents(eagerKeys);

    const device = detectDevice(ua);
    const seo = buildPageSeo(
      page.seoSection,
      enrichedSeoSection,
      mergedSections,
      isEagerRequest(matcherCtx),
    );

    const { seoSection: _seo, ...pageData } = page;

    // Same anti-cache-poisoning flag as loadCmsPageInternal — the homepage is the
    // highest-traffic, most-cached route, so it must not be exempt. The actual
    // X-Deco-Degraded header is emitted by the route `headers:` callback from
    // this `degraded` field (a reliable document-response channel).
    const degraded = getDegradedSections();
    if (degraded.length > 0) {
      console.warn(`[cms] home degraded — critical sections failed: ${degraded.join(", ")}`);
    }

    return {
      ...pageData,
      resolvedSections: normalizeUrlsInObject(mergedSections),
      deferredSections: normalizeUrlsInObject(page.deferredSections),
      degraded: degraded.length > 0,
      pagePath: "/",
      pageUrl: serverUrl.toString(),
      seo,
      device,
      flags,
      siteGlobals: { rawRefs: globals.rawRefs },
    };
  });

// ---------------------------------------------------------------------------
// Deferred section loader — resolves + enriches a single section on demand
// ---------------------------------------------------------------------------

/**
 * @deprecated Prefer TanStack native streaming via `deferredPromises` in the
 * route loader. This POST server function is kept for backward compatibility
 * and as a fallback for SPA navigations.
 */
export const loadDeferredSection = createServerFn({ method: "POST" })
  .inputValidator(
    (data: unknown) =>
      data as {
        component: string;
        /** @deprecated rawProps are now resolved server-side from the deferred props cache. */
        rawProps?: Record<string, any>;
        pagePath: string;
        pageUrl?: string;
        /** Original position in the page section list — preserved for correct SPA ordering. */
        index?: number;
      },
  )
  .handler(async (ctx) => {
    const { component, rawProps: clientRawProps, pagePath, pageUrl, index } = ctx.data;

    const originRequest = getRequest();
    const serverUrl = getRequestUrl().toString();
    const matcherCtx: MatcherContext = {
      userAgent: getRequestHeader("user-agent") ?? "",
      url: pageUrl || serverUrl,
      path: pagePath,
      cookies: getCookies(),
      request: originRequest,
    };

    // Resolve rawProps: prefer client-provided (backward compat), then server cache,
    // then re-extract from the page as a last resort (handles cross-isolate cache miss
    // on Cloudflare Workers and TTL expiry for slow-scrolling users).
    const rawProps =
      clientRawProps ??
      (index !== undefined ? getDeferredRawProps(pagePath, component, index) : null) ??
      (index !== undefined
        ? await reExtractRawProps(pagePath, component, index, matcherCtx)
        : null);

    if (!rawProps) {
      console.warn(
        `[CMS] Deferred section cache miss: ${component} at index ${index} on ${pagePath}`,
      );
      return null;
    }

    const section = await withTracing(
      "deco.section.deferred.load",
      () => resolveDeferredSection(component, rawProps, pagePath, matcherCtx),
      {
        "section.name": component,
        "page.path": pagePath,
        ...(typeof index === "number" ? { "section.index": index } : {}),
      },
    );
    if (!section) return null;

    // Preserve original index for correct ordering in SPA navigation merge
    if (index !== undefined) section.index = index;

    const request = new Request(pageUrl || serverUrl, {
      headers: originRequest.headers,
    });
    const enriched = await runSingleSectionLoader(section, request);

    // Anti-cache-poisoning: if this deferred section's loader failed (e.g. an
    // empty product shelf during a VTEX outage), do NOT mark it cacheable —
    // otherwise the empty shelf would be stored in serverFnCache and served to
    // every visitor for the full retention window. Flag it degraded instead.
    if (getDegradedSections().length > 0) {
      setResponseHeader("X-Deco-Degraded", "true");
    } else {
      // Signal to the worker entry that this response is safe to edge-cache.
      // Without this header, POST _serverFn responses are passed through
      // without caching (checkout actions, invoke mutations, etc.).
      setResponseHeader("X-Deco-Cacheable", "true");
    }

    return normalizeUrlsInObject(enriched);
  });

// ---------------------------------------------------------------------------
// Default pending component — shown during SPA navigation while loader runs
// ---------------------------------------------------------------------------

export function CmsPagePendingFallback() {
  return createElement(
    "div",
    { className: "w-full min-h-[60vh] flex flex-col gap-6 py-8" },
    createElement("div", {
      className: "skeleton animate-pulse w-full rounded",
      style: { aspectRatio: "1440/400", minHeight: 200 },
    }),
    createElement(
      "div",
      { className: "px-4 lg:px-8 flex flex-col gap-4" },
      createElement("div", { className: "skeleton animate-pulse w-48 h-8 rounded" }),
      createElement(
        "div",
        { className: "grid grid-cols-2 lg:grid-cols-4 gap-4" },
        ...Array.from({ length: 4 }, (_, i) =>
          createElement("div", {
            key: i,
            className: "skeleton animate-pulse w-full h-48 lg:h-64 rounded",
          }),
        ),
      ),
    ),
  );
}

/**
 * Default branded error boundary for CMS routes. Rendered when page resolution
 * throws (as opposed to returning no match, which is a 404 / not-found path) —
 * e.g. an uncaught throw in `resolveDecoPage` / `buildPageSeo` /
 * `resolveSiteGlobals` during a VTEX outage. Without an `errorComponent` the
 * loader rejection surfaces as a raw 500 white screen.
 *
 * This is the COLD-CACHE last resort: whenever a warm edge entry exists the
 * worker serves it as `STALE-ERROR` before the request ever reaches here.
 * Sites override via `cmsRouteConfig({ errorComponent })`.
 */
export function CmsPageErrorFallback(props: { reset?: () => void }) {
  return createElement(
    "div",
    { className: "min-h-[60vh] flex items-center justify-center px-4 text-center" },
    createElement(
      "div",
      { className: "max-w-md flex flex-col items-center gap-4" },
      createElement("h1", { className: "text-2xl font-bold" }, "Estamos com uma instabilidade"),
      createElement(
        "p",
        { className: "opacity-70" },
        "Não conseguimos carregar esta página agora. Tente novamente em instantes.",
      ),
      createElement(
        "button",
        {
          type: "button",
          className: "btn btn-primary",
          onClick: () => (props.reset ? props.reset() : undefined),
        },
        "Tentar de novo",
      ),
    ),
  );
}

// ---------------------------------------------------------------------------
// Route configuration factory
// ---------------------------------------------------------------------------

export interface CmsRouteOptions {
  /** Site name used in page titles (e.g. "Espaço Smart"). */
  siteName: string;
  /** Default page title when CMS page has no name. */
  defaultTitle: string;
  /** Default description for pages without section-contributed SEO. */
  defaultDescription?: string;
  /**
   * Search params to exclude from loader deps.
   * These params won't trigger a server re-fetch when they change.
   * Defaults to `["skuId"]` — variant selection is client-side only.
   */
  ignoreSearchParams?: string[];
  /** Custom pending component shown during SPA navigation. */
  pendingComponent?: () => any;
  /**
   * Custom error boundary rendered when the loader / page resolution throws.
   * Defaults to {@link CmsPageErrorFallback} (branded "instability" page with a
   * retry button) so an outage degrades gracefully instead of a raw 500.
   * Receives TanStack Router's `{ error, reset }`.
   */
  errorComponent?: (props: { error: Error; reset: () => void }) => any;
  /**
   * Delay (ms) before showing the pending component during SPA navigation.
   * If the loader resolves before this threshold, no pending UI is shown.
   * Prevents skeleton flash on fast cache-hit navigations. Default: 200.
   */
  pendingMs?: number;
  /**
   * Minimum display time (ms) for the pending component once shown.
   * Prevents jarring flash when data arrives shortly after the threshold.
   * Default: 300.
   */
  pendingMinMs?: number;
  /**
   * SSR mode for this route.
   * - `true` (default): Full SSR — loader + component render on server.
   * - `'data-only'`: Loader runs on server, component renders on client only.
   *   Use for interactive-heavy pages (PDP with zoom/variant selector).
   * - `false`: Everything runs on client only.
   */
  ssr?: boolean | "data-only";
  /**
   * Resolve `site.theme + site.global + site.pageSections` (the CMS `Site`
   * block) and merge them into every page's sections.
   *
   * Default: `true`. Set to `false` to restore pre-6.7.4 behavior for sites
   * that don't use the `Site` block and don't want it silently activated
   * (see #292) — this also skips the `Theme` section's `<style>` injection,
   * so the site's own `:root` CSS fallbacks apply instead.
   */
  resolveGlobals?: boolean;
}

type CmsPageLoaderData = {
  name?: string;
  cacheProfile?: CacheProfileName;
  degraded?: boolean;
  seo?: PageSeo;
  device?: Device;
  resolvedSections?: Array<{ component: string }>;
} | null;

// ---------------------------------------------------------------------------
// Page SEO assembly — merges page.seo block with section-contributed SEO
// ---------------------------------------------------------------------------

/**
 * Process the resolved SEO section from page.seo, apply title/description
 * templates, and merge with section-contributed SEO.
 *
 * `seoSection` is the raw (pre-loader) resolved section — its `props` are
 * used for the CMS-configured `titleTemplate`/`descriptionTemplate` fields,
 * which a loader transforming `{jsonLD} → {title, description}` may not
 * pass through unchanged. `enrichedSeoSection` must already have gone
 * through that registered section loader (e.g., SEOPDP transforms
 * {jsonLD: ProductDetailsPage} → {title, description, ...}) — batched
 * together with the body sections in `runSectionLoadersWithSeo` so a
 * commerce loader shared by both (the same product fetched by both the PDP
 * body section and the SeoPDP section) gets a chance to dedupe at the
 * fetch-cache layer instead of resolving the page twice (#355). This
 * function itself no longer runs any loader.
 */
function buildPageSeo(
  seoSection: ResolvedSection | null | undefined,
  enrichedSeoSection: ResolvedSection | null | undefined,
  enrichedSections: ResolvedSection[],
  isEager: boolean,
): PageSeo {
  // Secondary source: SEO sections embedded in the sections array.
  // `isEager` keeps structured-data suppression bot-aware: humans skip the
  // JSON-LD when `ignoreStructuredData` is on; crawlers still get it.
  const sectionSeo = extractSeoFromSections(enrichedSections, { isEager });

  // Site-wide SEO config from the "Site" app block — mirrors ctx.seo in
  // the original deco-cx/deco framework. Provides fallback title,
  // description, and templates when page-level seo doesn't supply them.
  const siteSeo = getSiteSeo();

  if (!seoSection) {
    // No page.seo block — use site-wide SEO as primary, section-contributed as secondary
    const merged: PageSeo = { ...sectionSeo };
    if (siteSeo.title && !merged.title) merged.title = siteSeo.title;
    if (siteSeo.description && !merged.description) merged.description = siteSeo.description;
    if (siteSeo.image && !merged.image) merged.image = siteSeo.image;

    // Apply site-level templates even when there is no page-level seo
    // section. Without this, pages whose title comes from a content
    // section (e.g. <h1> + sectionSeo) or from the site default would
    // skip `siteSeo.titleTemplate`, causing prod-vs-worker title drift.
    const titleTemplate = effectiveTemplate(siteSeo.titleTemplate);
    const descTemplate = effectiveTemplate(siteSeo.descriptionTemplate);
    if (titleTemplate && merged.title) {
      merged.title = titleTemplate.replace("%s", merged.title);
    }
    if (descTemplate && merged.description) {
      merged.description = descTemplate.replace("%s", merged.description);
    }

    return merged;
  }

  // enrichedSeoSection should always be present once seoSection is, but
  // fall back to the raw section's props (pre-loader) if the loader batch
  // somehow dropped it — same "use the raw resolved props" resilience the
  // old inline try/catch had around the loader call.
  const enrichedProps = (enrichedSeoSection ?? seoSection).props;
  const pageSeo = extractSeoFromProps(enrichedProps, { isEager });

  // Replicate original SeoV2 loader logic: `_title ?? appTitle`
  // When the page's seo block doesn't have a title/description,
  // fall back to the Site app's seo config.
  if (!pageSeo.title && siteSeo.title) pageSeo.title = siteSeo.title;
  if (!pageSeo.description && siteSeo.description) pageSeo.description = siteSeo.description;
  if (!pageSeo.image && siteSeo.image) pageSeo.image = siteSeo.image;

  // Apply title/description templates.
  // Priority: page-level template → site-level template → no-op.
  // This mirrors the original: `(titleTemplate ?? "").trim().length === 0 ? "%s" : titleTemplate`
  const rawProps = seoSection.props;
  const titleTemplate =
    effectiveTemplate(rawProps.titleTemplate as string | undefined) ??
    effectiveTemplate(siteSeo.titleTemplate);
  const descTemplate =
    effectiveTemplate(rawProps.descriptionTemplate as string | undefined) ??
    effectiveTemplate(siteSeo.descriptionTemplate);

  if (titleTemplate && pageSeo.title) {
    pageSeo.title = titleTemplate.replace("%s", pageSeo.title);
  }
  if (descTemplate && pageSeo.description) {
    pageSeo.description = descTemplate.replace("%s", pageSeo.description);
  }

  // Primary source (page.seo) overrides secondary (section-contributed).
  // Only truthy fields in pageSeo override — undefined keys don't clear sectionSeo.
  return { ...sectionSeo, ...pageSeo };
}

/** Returns a non-trivial template string, or undefined for "%s" / empty / blank. */
function effectiveTemplate(tmpl: string | undefined): string | undefined {
  if (!tmpl || tmpl.trim() === "" || tmpl.trim() === "%s") return undefined;
  return tmpl;
}

// ---------------------------------------------------------------------------
// Head metadata builder
// ---------------------------------------------------------------------------

/**
 * Build TanStack Router `head()` metadata from page-level and section-contributed SEO.
 * Emits: title, description, canonical, OG tags, Twitter Card, robots directive.
 */
function buildHead(
  loaderData: CmsPageLoaderData | undefined,
  siteName: string,
  defaultTitle: string,
  defaultDescription?: string,
) {
  const seo = loaderData?.seo;
  const title = seo?.title
    ? seo.title
    : loaderData?.name
      ? `${loaderData.name} | ${siteName}`
      : defaultTitle;
  const description = seo?.description || defaultDescription;
  const image = seo?.image;
  const canonical = seo?.canonical;
  const noIndex = seo?.noIndexing;

  const meta: Record<string, string>[] = [{ title }];

  if (description) {
    meta.push({ name: "description", content: description });
  }

  // Robots — always emit a directive so crawlers see an explicit signal
  meta.push({
    name: "robots",
    content: noIndex
      ? "noindex, nofollow"
      : "index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1",
  });

  // Open Graph
  meta.push({ property: "og:title", content: title });
  if (description) meta.push({ property: "og:description", content: description });
  if (image) meta.push({ property: "og:image", content: image });
  meta.push({ property: "og:type", content: seo?.type || "website" });
  if (canonical) meta.push({ property: "og:url", content: canonical });

  // Twitter Card
  meta.push({ name: "twitter:card", content: image ? "summary_large_image" : "summary" });
  meta.push({ name: "twitter:title", content: title });
  if (description) meta.push({ name: "twitter:description", content: description });
  if (image) meta.push({ name: "twitter:image", content: image });

  const links: Record<string, string>[] = [];
  if (canonical) {
    links.push({ rel: "canonical", href: canonical });
  }

  // Modulepreload hints for eager section chunks
  if (loaderData?.resolvedSections) {
    for (const s of loaderData.resolvedSections) {
      const chunkFile = sectionChunkMap[s.component];
      if (chunkFile) {
        links.push({ rel: "modulepreload", href: `/${chunkFile}` });
      }
    }
  }

  // JSON-LD structured data — rendered as <script type="application/ld+json"> in <head>
  const scripts: Array<{ type: string; children: string }> = [];
  if (seo?.jsonLDs?.length) {
    for (const jsonLD of seo.jsonLDs) {
      scripts.push({
        type: "application/ld+json",
        children: JSON.stringify(jsonLD),
      });
    }
  }

  return { meta, links, scripts };
}

/**
 * Returns a TanStack Router route config object for a CMS catch-all route.
 * Spread the result into your `createFileRoute("/$")({...})` call.
 *
 * Includes: loaderDeps, loader, headers, head (with full SEO), staleTime/gcTime.
 * Does NOT include: component, notFoundComponent (site provides these).
 *
 * SEO metadata is extracted from sections registered via `registerSeoSections()`.
 * The `head()` function emits title, description, canonical, OG tags, and robots.
 */
export function cmsRouteConfig(options: CmsRouteOptions) {
  const {
    siteName,
    defaultTitle,
    defaultDescription,
    ignoreSearchParams = ["skuId"],
    pendingComponent,
    pendingMs = 200,
    pendingMinMs = 300,
    ssr: ssrMode,
    errorComponent = CmsPageErrorFallback,
    resolveGlobals,
  } = options;

  const ignoreSet = new Set(ignoreSearchParams);

  return {
    // Catch-all search validation: preserve all URL search params so they
    // reach loaderDeps. Without this, TanStack Router may strip unknown
    // params (e.g. ?q=, filter.*, page, sort) during SPA navigation.
    validateSearch: (search: Record<string, unknown>) => search as Record<string, string>,

    loaderDeps: ({ search }: { search: Record<string, string> }) => {
      const filtered = Object.fromEntries(
        Object.entries(search ?? {}).filter(([k]) => !ignoreSet.has(k)),
      );
      return {
        search: Object.keys(filtered).length ? filtered : undefined,
      };
    },

    loader: async ({
      params,
      deps,
    }: {
      params: { _splat?: string };
      deps: { search?: Record<string, string> };
    }) => {
      const basePath = "/" + (params._splat || "");
      const searchStr = deps.search
        ? "?" + new URLSearchParams(deps.search as Record<string, string>).toString()
        : "";
      const page = await loadCmsPage({
        data: { path: basePath + searchStr, resolveGlobals },
      });
      if (!page) return page;

      if (!isServer && page.resolvedSections) {
        const keys = page.resolvedSections.map((s: ResolvedSection) => s.component);
        await preloadSectionComponents(keys);
      }

      // Deferred sections use client-side IntersectionObserver loading.
      // DecoPageRenderer renders skeletons (LoadingFallback) during SSR and
      // loads full section content via _serverFn when scrolled into view.
      //
      // Previously, SSR streaming via TanStack <Await> resolved ALL deferred
      // sections server-side and streamed them in the initial HTML. This caused
      // the browser to load ALL product shelf images at once (~3x more image
      // requests than the IntersectionObserver path). Client SPA navigation
      // also blocked on await Promise.all() for all deferred sections.
      //
      // The IO path (DeferredSectionWrapper) only fetches section data when
      // the skeleton scrolls into view, matching Fresh/Deno partial behavior
      // and significantly reducing initial image load and TBT.
      return page;
    },

    ...(pendingComponent ? { pendingComponent } : {}),
    pendingMs,
    pendingMinMs,
    errorComponent,
    ...(ssrMode !== undefined ? { ssr: ssrMode } : {}),

    ...routeCacheDefaults("product"),

    headers: ({ loaderData }: { loaderData?: CmsPageLoaderData }) => {
      const profile = loaderData?.cacheProfile ?? "listing";
      const headers = cacheHeaders(profile);
      // Emit the degraded flag on the DOCUMENT response via the route headers
      // callback — the reliable channel (same one cacheHeaders rides), unlike
      // setResponseHeader inside the server fn which may not reach the document.
      // The worker treats a 200 + X-Deco-Degraded like a 5xx (no store, serve
      // stale) to prevent caching an empty page during a VTEX outage.
      if (loaderData?.degraded) headers["X-Deco-Degraded"] = "true";
      return headers;
    },

    head: ({ loaderData }: { loaderData?: CmsPageLoaderData }) =>
      buildHead(loaderData, siteName, defaultTitle, defaultDescription),
  };
}

/**
 * Returns a TanStack Router route config for the CMS homepage route.
 * Spread into `createFileRoute("/")({...})`.
 *
 * Like `cmsRouteConfig`, emits full SEO head metadata from section-contributed data.
 */
export function cmsHomeRouteConfig(options: {
  defaultTitle: string;
  defaultDescription?: string;
  /** Site name for OG title composition. Defaults to defaultTitle. */
  siteName?: string;
  pendingComponent?: () => any;
  /** Delay (ms) before showing pending component. Default: 200. */
  pendingMs?: number;
  /** Minimum display time (ms) for pending component. Default: 300. */
  pendingMinMs?: number;
  /** Error boundary for loader throws. Defaults to {@link CmsPageErrorFallback}. */
  errorComponent?: (props: { error: Error; reset: () => void }) => any;
  /** See `CmsRouteOptions.resolveGlobals` — default `true`. */
  resolveGlobals?: boolean;
}) {
  const {
    defaultTitle,
    defaultDescription,
    siteName,
    pendingMs = 200,
    pendingMinMs = 300,
    errorComponent = CmsPageErrorFallback,
    resolveGlobals,
  } = options;

  return {
    loader: async () => {
      const page = await loadCmsHomePage({ data: { resolveGlobals } });
      if (!page) return page;

      if (!isServer && page.resolvedSections) {
        const keys = page.resolvedSections.map((s: ResolvedSection) => s.component);
        await preloadSectionComponents(keys);
      }

      // Deferred sections use client-side IntersectionObserver loading.
      // See cmsRouteConfig loader for rationale.
      return page;
    },
    ...(options.pendingComponent ? { pendingComponent: options.pendingComponent } : {}),
    pendingMs,
    pendingMinMs,
    errorComponent,
    ...routeCacheDefaults("static"),
    headers: ({ loaderData }: { loaderData?: CmsPageLoaderData }) => {
      const headers = cacheHeaders("static");
      if (loaderData?.degraded) headers["X-Deco-Degraded"] = "true";
      return headers;
    },
    head: ({ loaderData }: { loaderData?: CmsPageLoaderData }) =>
      buildHead(loaderData, siteName ?? defaultTitle, defaultTitle, defaultDescription),
  };
}
