// @decocms/blocks: the v8 runtime API. The CLI, protocol and helpers live on
// their own subpaths (`/cli`, `/protocol`, `/fetch`, `/analytics`, `/secrets`).
export {
  type Analytics,
  type Block,
  type BlockFunction,
  type Blocks,
  type Client,
  type CMS,
  type CMSError,
  createCMS,
  DRAFT_COOKIE,
  type DraftPointer,
  draftCookie,
  draftPointer,
  formatDraftPointer,
  type Lazy,
  type ListOptions,
  type Loader,
  type Match,
  matchRoute,
  type Page,
  parseDraftPointer,
  type Redirect,
  type Result,
  type Route,
  remoteLoader,
  resetForTests,
  type Secret,
  type Seo,
  type Snapshot,
  type Telemetry,
  type TelemetryConfig,
  type Variant,
} from "./v8/index.ts";
