#!/usr/bin/env bun
/**
 * readme.ts — generates the skill index in README.md from the skills themselves.
 *
 * The repo this pattern comes from asks contributors, in prose, to "update its
 * row if you change a skill's frontmatter". That instruction is drift with extra
 * steps: the row and the skill are edited by different people at different times,
 * and nothing notices when they disagree. So the index is generated, and CI runs
 * `--check` to fail a PR whose README no longer matches what is on disk.
 *
 * Usage:
 *   bun run skills:readme        # rewrite the generated block
 *   bun run skills:readme:check  # exit 1 if it is stale
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

// Copied from decocms/migrations scripts/readme.ts — keep in sync there.
const root = new URL("../.agents/skills/", import.meta.url).pathname;
const README = join(root, "README.md");
const START = "<!-- skills:start -->";
const END = "<!-- skills:end -->";
const SKIP_DIRS = new Set([".git", "node_modules", "scripts", ".github"]);

/** Human heading per top-level area. Unlisted areas still render, under their own name. */
const AREAS: Record<string, string> = {
  "": "Framework and package skills",
};

function skills(): { path: string; area: string; name: string; description: string }[] {
  const out: { path: string; area: string; name: string; description: string }[] = [];
  const walk = (dir: string) => {
    for (const e of readdirSync(dir, { withFileTypes: true })) {
      if (e.isDirectory()) {
        if (!SKIP_DIRS.has(e.name)) walk(join(dir, e.name));
      } else if (e.name === "SKILL.md") {
        const rel = relative(root, dir);
        if (rel === "template") continue;
        const text = readFileSync(join(dir, e.name), "utf8");
        const fm = text.startsWith("---\n") ? text.slice(4, text.indexOf("\n---", 4)) : "";
        const get = (k: string) =>
          fm
            .split("\n")
            .find((l) => l.startsWith(`${k}:`))
            ?.slice(k.length + 1)
            .trim()
            .replace(/^["']|["']$/g, "") ?? "";
        out.push({
          path: rel,
          area: rel.includes("/") ? rel.split("/")[0] : "",
          name: rel.split("/").pop() as string,
          description: get("description"),
        });
      }
    }
  };
  walk(root);
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

const all = skills();
const areas = [...new Set(all.map((s) => s.area))].sort();

let block = "";
for (const area of areas) {
  const rows = all.filter((s) => s.area === area);
  block += `\n### ${AREAS[area] ?? (area || "Top level")}\n\n`;
  block += "| Skill | What it covers |\n|---|---|\n";
  for (const r of rows) block += `| [\`${r.path}/\`](${r.path}/SKILL.md) | ${r.description || "—"} |\n`;
}
block += `\n_${all.length} skill(s). This table is generated by \`scripts/skills-readme.ts\` — edit the skill, not the row._\n`;

const current = readFileSync(README, "utf8");
const a = current.indexOf(START);
const b = current.indexOf(END);
if (a === -1 || b === -1) {
  console.error(`README.md is missing the ${START} / ${END} markers — cannot place the generated index.`);
  process.exit(1);
}
const next = `${current.slice(0, a + START.length)}\n${block}${current.slice(b)}`;

if (process.argv.includes("--check")) {
  if (next !== current) {
    console.error("README.md skill index is stale. Run `bun run skills:readme` and commit the result.");
    process.exit(1);
  }
  console.log(`README ok — index matches ${all.length} skill(s) on disk`);
} else {
  writeFileSync(README, next);
  console.log(`README updated — ${all.length} skill(s) across ${areas.length} area(s)`);
}
