/**
 * Applies convention-based section metadata generated by generate-sections.ts.
 *
 * Reads the generated sectionMeta/syncComponents/loadingFallbacks and calls
 * the appropriate registration functions — replacing manual calls to
 * registerSectionsSync, setAsyncRenderingConfig, registerCacheableSections,
 * registerLayoutSections, registerSeoSections, and registerSection.
 */
import {
  type ApplySectionConventionsInput,
  applyClientSectionConventions,
} from "./clientConventions";
import {
  type AsyncRenderingConfig,
  getAsyncRenderingConfig,
  registerAlwaysDeferSections,
  registerEagerSections,
  registerFallbackPropsSections,
  registerNeverDeferSections,
  registerSeoSections,
  setAsyncRenderingConfig,
} from "./resolve";
import {
  type CacheableSectionInput,
  registerCacheableSections,
  registerLayoutSections,
} from "./sectionLoaders";

export type { ApplySectionConventionsInput, SectionMetaEntry } from "./clientConventions";

export function applySectionConventions(input: ApplySectionConventionsInput): void {
  const { meta } = input;

  // Registry-only registrations (clientOnly, LoadingFallback, renderJson, sync
  // components) live in clientConventions.ts so browser entries can run them
  // without this module's resolver/section-loader graph.
  applyClientSectionConventions(input);

  const eagerSections: string[] = [];
  const neverDeferSections: string[] = [];
  const alwaysDeferSections: string[] = [];
  const layoutSections: string[] = [];
  const seoSections: string[] = [];
  const cacheableSections: Record<string, CacheableSectionInput> = {};
  const fallbackPropsSections: Record<string, string[]> = {};

  for (const [key, entry] of Object.entries(meta)) {
    if (entry.eager) eagerSections.push(key);
    if (entry.neverDefer) neverDeferSections.push(key);
    if (entry.deferred) alwaysDeferSections.push(key);
    if (entry.layout) layoutSections.push(key);
    if (entry.seo) seoSections.push(key);
    if (entry.cache) cacheableSections[key] = entry.cache as CacheableSectionInput;
    if (entry.fallbackProps?.length) fallbackPropsSections[key] = entry.fallbackProps;
  }

  if (eagerSections.length > 0) {
    registerEagerSections(eagerSections);
  }

  if (neverDeferSections.length > 0) {
    registerNeverDeferSections(neverDeferSections);
  }

  if (alwaysDeferSections.length > 0) {
    registerAlwaysDeferSections(alwaysDeferSections);
  }

  // Always initialize asyncConfig so CMS Lazy deferral (`respectCmsLazy`) is
  // active — this is what makes the admin ⚡ toggle the source of truth. Without
  // it, asyncConfig stays null, `useAsync` is false in resolveDecoPage, and
  // even editor-marked ⚡ sections render eagerly. (The default foldThreshold is
  // Infinity, so position-based deferral stays off unless a site opts in.)
  const existing: Partial<AsyncRenderingConfig> = getAsyncRenderingConfig() ?? {};
  setAsyncRenderingConfig({
    ...existing,
    alwaysEager: [...(existing.alwaysEager ?? []), ...eagerSections],
  });

  if (layoutSections.length > 0) {
    registerLayoutSections(layoutSections);
  }

  if (seoSections.length > 0) {
    registerSeoSections(seoSections);
  }

  if (Object.keys(cacheableSections).length > 0) {
    registerCacheableSections(cacheableSections);
  }

  if (Object.keys(fallbackPropsSections).length > 0) {
    registerFallbackPropsSections(fallbackPropsSections);
  }
}
