/**
 * Hand-tokenised code for the landing's mockups (the old landing.html markup, as JSX), coloured
 * with the syntax tokens (text-syn-*). The journey panes use the components below; the stepper's
 * two code panes are HTML strings (the Prism markup the old page produced at runtime, frozen here
 * with utility classes so nothing highlights in the browser).
 */
import type { ReactNode } from 'react'

type C = { children: ReactNode; className?: string }
const span = (cls: string) =>
  function Token({ children, className }: C) {
    return <span className={className ? `${cls} ${className}` : cls}>{children}</span>
  }
export const K = span('text-syn-keyword')
export const T = span('text-syn-type')
export const P = span('text-syn-property')
export const S = span('text-syn-string')
export const N = span('text-syn-number')
export const F = span('text-syn-function')
export const Cm = span('text-syn-comment italic')
/** A JSDoc tag inside a comment. */
export const Ck = span('text-fg not-italic font-semibold')
/** One numbered line of a numbered pane (the number is a CSS counter the pane resets). */
export const L = span(
  'block whitespace-pre [counter-increment:ln] overflow-hidden text-ellipsis before:content-[counter(ln)] before:inline-block before:w-4 before:mr-3 before:text-right before:text-quiet before:tabular-nums before:select-none',
)

const TOKEN = {
  keyword: 'text-syn-keyword',
  punctuation: 'text-syn-punctuation',
  operator: 'text-syn-operator',
  string: 'text-syn-string',
  comment: 'text-syn-comment italic',
  function: 'text-syn-function',
  constant: 'text-syn-type',
}
const tok = (kind: keyof typeof TOKEN, text: string) => `<span class="${TOKEN[kind]}">${text}</span>`
const kw = (t: string) => tok('keyword', t)
const pu = (t: string) => tok('punctuation', t)
const op = (t: string) => tok('operator', t)
const str = (t: string) => tok('string', t)
const cm = (t: string) => tok('comment', t)
const fn = (t: string) => tok('function', t)

/** Step 1 pane (.deco/blocks.ts). */
export const STEP1_HTML = [
  cm('// experiments.ts: the function you already have'),
  `${kw('export')} ${kw('default')} ${kw('function')} ${fn('experiments')}${pu('(')}input${op(':')} Experiments${pu(')')} ${pu('{')}`,
  `  ${kw('return')} ${pu('{')} newCheckout${op(':')} ${fn('roll')}${pu('(')}input${pu('.')}newCheckout${pu(')')}${pu(',')} ${cm('/* … */')} ${pu('}')}${pu(';')}`,
  pu('}'),
  '',
  cm('// .deco/blocks.ts: give it a name in a block map'),
  `${kw('import')} ${kw('type')} ${pu('{')} Blocks ${pu('}')} ${kw('from')} ${str('"@decocms/blocks"')}${pu(';')}`,
  `${kw('import')} experiments ${kw('from')} ${str('"../experiments"')}${pu(';')}`,
  '',
  `${kw('export')} ${kw('default')} ${pu('{')} experiments ${pu('}')} satisfies Blocks${pu(';')}`,
].join('\n')

/** Step 3 pane (cms.ts). */
export const STEP3_HTML = [
  `${kw('import')} ${pu('{')} createCMS ${pu('}')} ${kw('from')} ${str('"@decocms/blocks"')}${pu(';')}`,
  `${kw('import')} blocks ${kw('from')} ${str('"./.deco/blocks"')}${pu(';')}`,
  `${kw('import')} content ${kw('from')} ${str('"./.deco/content.gen"')}${pu(';')}`,
  '',
  cm('// .deco/content.gen is generated by `deco content`; don\'t edit it.'),
  cm('// With a site and token, production reads the hosted Deco CMS'),
  cm('// and sends sampled telemetry; without them, it reads that generated module.'),
  `${kw('export')} ${kw('const')} cms ${op('=')} ${fn('createCMS')}${pu('(')}${pu('{')}`,
  `  blocks${pu(',')}`,
  `  content${pu(',')}`,
  `  ${cm("// your site's ID and site token (secret) for the hosted Deco CMS")}`,
  `  site${op(':')} process${pu('.')}env${pu('.')}${tok('constant', 'DECO_SITE')}${pu(',')}`,
  `  token${op(':')} process${pu('.')}env${pu('.')}${tok('constant', 'DECO_SITE_TOKEN')}${pu(',')}`,
  `${pu('}')}${pu(')')}${pu(';')}`,
].join('\n')
