// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests
import * as loaders_Author from "./loaders/Author";
import * as loaders_BlogPostPage from "./loaders/BlogPostPage";
import * as loaders_Blogpost from "./loaders/Blogpost";
import * as loaders_BlogpostListing from "./loaders/BlogpostListing";
import * as loaders_BlogRelatedPosts from "./loaders/BlogRelatedPosts";
import * as loaders_Category from "./loaders/Category";
import * as loaders_GetCategories from "./loaders/GetCategories";

const manifest = {
	name: "blog",
	loaders: {
		"blog/loaders/Author": loaders_Author,
		"blog/loaders/Blogpost": loaders_Blogpost,
		"blog/loaders/BlogPostPage": loaders_BlogPostPage,
		"blog/loaders/BlogpostListing": loaders_BlogpostListing,
		"blog/loaders/BlogRelatedPosts": loaders_BlogRelatedPosts,
		"blog/loaders/Category": loaders_Category,
		"blog/loaders/GetCategories": loaders_GetCategories,
	},
	actions: {},
	sections: {},
} as const;

export type Manifest = typeof manifest;
export default manifest;
