// AUTO-GENERATED by scripts/generate-manifests.ts — DO NOT EDIT
// This file is checked into source control and updated via: npm run generate:manifests

import * as actions_address from "./actions/address";
import * as actions_analytics_sendEvent from "./actions/analytics/sendEvent";
import * as actions_auth from "./actions/auth";
import * as actions_checkout from "./actions/checkout";
import * as actions_masterData from "./actions/masterData";
import * as actions_misc from "./actions/misc";
import * as actions_newsletter from "./actions/newsletter";
import * as actions_orders from "./actions/orders";
import * as actions_profile from "./actions/profile";
import * as actions_session from "./actions/session";
import * as actions_trigger from "./actions/trigger";
import * as actions_wishlist from "./actions/wishlist";
import * as loaders_address from "./loaders/address";
import * as loaders_autocomplete from "./loaders/autocomplete";
import * as loaders_brands from "./loaders/brands";
import * as loaders_cart from "./loaders/cart";
import * as loaders_catalog from "./loaders/catalog";
import * as loaders_collections from "./loaders/collections";
import * as loaders_legacy from "./loaders/legacy";
import * as loaders_logistics from "./loaders/logistics";
import * as loaders_navbar from "./loaders/navbar";
import * as loaders_orders from "./loaders/orders";
import * as loaders_pageType from "./loaders/pageType";
import * as loaders_payment from "./loaders/payment";
import * as loaders_profile from "./loaders/profile";
import * as loaders_promotion from "./loaders/promotion";
import * as loaders_search from "./loaders/search";
import * as loaders_session from "./loaders/session";
import * as loaders_user from "./loaders/user";
import * as loaders_wishlist from "./loaders/wishlist";
import * as loaders_wishlistProducts from "./loaders/wishlistProducts";
import * as loaders_workflow from "./loaders/workflow";

const manifest = {
	name: "vtex",
	loaders: {
		"vtex/loaders/address": loaders_address,
		"vtex/loaders/autocomplete": loaders_autocomplete,
		"vtex/loaders/brands": loaders_brands,
		"vtex/loaders/cart": loaders_cart,
		"vtex/loaders/catalog": loaders_catalog,
		"vtex/loaders/collections": loaders_collections,
		"vtex/loaders/legacy": loaders_legacy,
		"vtex/loaders/logistics": loaders_logistics,
		"vtex/loaders/navbar": loaders_navbar,
		"vtex/loaders/orders": loaders_orders,
		"vtex/loaders/pageType": loaders_pageType,
		"vtex/loaders/payment": loaders_payment,
		"vtex/loaders/profile": loaders_profile,
		"vtex/loaders/promotion": loaders_promotion,
		"vtex/loaders/search": loaders_search,
		"vtex/loaders/session": loaders_session,
		"vtex/loaders/user": loaders_user,
		"vtex/loaders/wishlist": loaders_wishlist,
		"vtex/loaders/wishlistProducts": loaders_wishlistProducts,
		"vtex/loaders/workflow": loaders_workflow,
	},
	actions: {
		"vtex/actions/address": actions_address,
		"vtex/actions/analytics/sendEvent": actions_analytics_sendEvent,
		"vtex/actions/auth": actions_auth,
		"vtex/actions/checkout": actions_checkout,
		"vtex/actions/masterData": actions_masterData,
		"vtex/actions/misc": actions_misc,
		"vtex/actions/newsletter": actions_newsletter,
		"vtex/actions/orders": actions_orders,
		"vtex/actions/profile": actions_profile,
		"vtex/actions/session": actions_session,
		"vtex/actions/trigger": actions_trigger,
		"vtex/actions/wishlist": actions_wishlist,
	},
	sections: {},
} as const;

export type Manifest = typeof manifest;
export default manifest;
