// AUTO-GENERATED by @decocms/blocks-cli scripts/generate-app-schemas.ts — DO NOT EDIT
// Regenerate from this package's root: bun run generate:schemas
//
// Real props schemas for this app's loaders/actions, keyed by CMS key
// (both bare and `.ts` forms). Registered into the admin meta via
// registerAppSchemas() so the Studio can render real props forms instead
// of the __resolveType-only stubs from registerCommerceLoaders().
import type { BlockPropsSchema } from "@decocms/blocks/cms/client";

const s0: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"nullable": true,
			"title": "Slug"
		},
		"skuId": {
			"type": "string",
			"nullable": true,
			"title": "SkuId"
		},
		"indexingSkus": {
			"type": "boolean",
			"nullable": true,
			"description": "When true, PDP pages with ?skuId remain indexable",
			"title": "IndexingSkus"
		},
		"preferDescription": {
			"type": "boolean",
			"nullable": true,
			"description": "Use product.description instead of metaTagDescription for SEO",
			"title": "PreferDescription"
		},
		"leanVariants": {
			"type": "boolean",
			"nullable": true,
			"description": "Use lean variant transform for hasVariant[]. Defaults to false on PDPs:\nvariant selectors need image[] and real inventoryLevel to render thumbnails\nand per-SKU stock state, so a full toProduct(level=1) is the safe default.\nOpt-in only if payload size becomes a problem.",
			"title": "LeanVariants"
		},
		"variantIncludeImage": {
			"type": "boolean",
			"nullable": true,
			"description": "When leanVariants is true, still include image[0] on each variant. Default true.",
			"title": "VariantIncludeImage"
		},
		"variantIncludeInventory": {
			"type": "boolean",
			"nullable": true,
			"description": "When leanVariants is true, still include inventoryLevel on each variant. Default true.",
			"title": "VariantIncludeInventory"
		}
	}
};
const s1: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"props": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"collection": {
							"type": "string",
							"title": "Collection"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"collection"
					],
					"title": "CollectionProps"
				},
				{
					"type": "object",
					"properties": {
						"query": {
							"type": "string",
							"title": "Query"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"fuzzy": {
							"type": "string",
							"nullable": true,
							"title": "Fuzzy"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"query"
					],
					"title": "QueryProps"
				},
				{
					"type": "object",
					"properties": {
						"ids": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "Ids"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"ids"
					],
					"title": "ProductIDProps"
				},
				{
					"type": "object",
					"properties": {
						"query": {
							"type": "string",
							"nullable": true,
							"title": "Query"
						},
						"facets": {
							"type": "string",
							"title": "Facets"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"facets"
					],
					"title": "FacetsProps"
				}
			],
			"nullable": true,
			"title": "Props"
		}
	}
};
const s2: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query",
			"description": "Overrides the search term used to fetch the listing."
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Items per page",
			"description": "Number of products per page to display."
		},
		"sort": {
			"type": "string",
			"enum": [
				"",
				"price:desc",
				"price:asc",
				"orders:desc",
				"name:desc",
				"name:asc",
				"release:desc",
				"discount:desc"
			],
			"nullable": true,
			"title": "Sorting",
			"description": "Order in which products are returned."
		},
		"fuzzy": {
			"type": "string",
			"enum": [
				"automatic",
				"disabled",
				"enabled"
			],
			"nullable": true,
			"title": "Fuzzy",
			"description": "Controls Intelligent Search typo tolerance."
		},
		"page": {
			"type": "number",
			"nullable": true,
			"title": "Page offset",
			"description": "Starting page (0-indexed) for the listing query."
		},
		"selectedFacets": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"key": {
						"type": "string",
						"title": "Key"
					},
					"value": {
						"type": "string",
						"title": "Value"
					}
				},
				"required": [
					"key",
					"value"
				]
			},
			"nullable": true,
			"title": "Selected Facets",
			"description": "Override selected facets from the URL (e.g. force a collection)."
		},
		"hideUnavailableItems": {
			"type": "boolean",
			"nullable": true,
			"title": "Hide Unavailable Items",
			"description": "Do not return out-of-stock items."
		}
	}
};
const s3: BlockPropsSchema = {
	"description": "Look up a postal address by country + postal code (public API).",
	"type": "object",
	"additionalProperties": true
};
const s4: BlockPropsSchema = {
	"description": "Fetch addresses for the currently authenticated user.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s5: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"title": "Query"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Count"
		},
		"showSponsored": {
			"type": "boolean",
			"nullable": true,
			"title": "ShowSponsored"
		},
		"placement": {
			"type": "string",
			"nullable": true,
			"title": "Placement"
		},
		"fuzzy": {
			"type": "string",
			"nullable": true,
			"title": "Fuzzy"
		}
	},
	"required": [
		"query"
	]
};
const s6: BlockPropsSchema = {
	"description": "Get a single brand by ID, as schema.org Brand.",
	"type": "object",
	"additionalProperties": true
};
const s7: BlockPropsSchema = {
	"description": "List brands from the VTEX catalog, transformed to schema.org Brand format.",
	"type": "object",
	"properties": {
		"filterInactive": {
			"type": "boolean",
			"nullable": true,
			"description": "When true, only returns active brands.",
			"default": false,
			"title": "FilterInactive"
		}
	},
	"nullable": true
};
const s8: BlockPropsSchema = {
	"description": "Fetch the current cart (OrderForm).\n\nWhen `orderFormId` is provided the existing cart is retrieved;\notherwise a fresh OrderForm is created via POST.",
	"type": "object",
	"additionalProperties": true
};
const s9: BlockPropsSchema = {
	"description": "Get all brands.",
	"type": "object",
	"properties": {}
};
const s10: BlockPropsSchema = {
	"description": "Get the category tree up to a given depth level.",
	"type": "object",
	"additionalProperties": true
};
const s11: BlockPropsSchema = {
	"description": "Get cross-selling products.",
	"type": "object",
	"additionalProperties": true
};
const s12: BlockPropsSchema = {
	"description": "Get facets/filters for a search term.",
	"type": "object",
	"additionalProperties": true
};
const s13: BlockPropsSchema = {
	"description": "Get the page type for a given term/path.",
	"type": "object",
	"additionalProperties": true
};
const s14: BlockPropsSchema = {
	"description": "Get a product by productId or skuId.",
	"type": "object",
	"properties": {
		"productId": {
			"type": "string",
			"nullable": true,
			"title": "ProductId"
		},
		"skuId": {
			"type": "string",
			"nullable": true,
			"title": "SkuId"
		}
	}
};
const s15: BlockPropsSchema = {
	"description": "Get product specifications (private API).",
	"type": "object",
	"additionalProperties": true
};
const s16: BlockPropsSchema = {
	"description": "Get product SKU variations.",
	"type": "object",
	"additionalProperties": true
};
const s17: BlockPropsSchema = {
	"description": "Search products using the VTEX Catalog API.",
	"type": "object",
	"properties": {
		"fq": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			],
			"nullable": true,
			"title": "Fq"
		},
		"ft": {
			"type": "string",
			"nullable": true,
			"title": "Ft"
		},
		"sort": {
			"type": "string",
			"enum": [
				"",
				"OrderByTopSaleDESC",
				"OrderByReleaseDateDESC",
				"OrderByBestDiscountDESC",
				"OrderByPriceDESC",
				"OrderByPriceASC",
				"OrderByNameASC",
				"OrderByNameDESC",
				"OrderByScoreDESC"
			],
			"nullable": true,
			"title": "Sort"
		},
		"from": {
			"type": "number",
			"nullable": true,
			"title": "From"
		},
		"to": {
			"type": "number",
			"nullable": true,
			"title": "To"
		}
	}
};
const s18: BlockPropsSchema = {
	"description": "Fetch collections, optionally filtering by search term.\n\nWithout a term returns up to 3 000 collections; with a term\nreturns the first 15 matches. Results are mapped to a simple\n`{ value, label }` list suitable for dropdowns / selectors.\n\nNote: uses the **pvt** (private) endpoint — requires appKey/appToken.",
	"type": "object",
	"additionalProperties": true
};
const s19: BlockPropsSchema = {
	"description": "Mirrors the original deco-cx/apps PLP loader:\n\n1. Resolve facets from CMS props or Page Type API\n2. Call product_search AND facets APIs in parallel (same params)\n3. Transform products to schema.org format\n4. Transform facets to FilterToggle format\n5. Build pagination from IS response",
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query",
			"description": "Overrides the search term used to fetch the listing."
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Items per page",
			"description": "Number of products per page to display."
		},
		"sort": {
			"type": "string",
			"enum": [
				"",
				"price:desc",
				"price:asc",
				"orders:desc",
				"name:desc",
				"name:asc",
				"release:desc",
				"discount:desc"
			],
			"nullable": true,
			"title": "Sorting",
			"description": "Order in which products are returned."
		},
		"fuzzy": {
			"type": "string",
			"enum": [
				"automatic",
				"disabled",
				"enabled"
			],
			"nullable": true,
			"title": "Fuzzy",
			"description": "Controls Intelligent Search typo tolerance."
		},
		"page": {
			"type": "number",
			"nullable": true,
			"title": "Page offset",
			"description": "Starting page (0-indexed) for the listing query."
		},
		"selectedFacets": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"key": {
						"type": "string",
						"title": "Key"
					},
					"value": {
						"type": "string",
						"title": "Value"
					}
				},
				"required": [
					"key",
					"value"
				]
			},
			"nullable": true,
			"title": "Selected Facets",
			"description": "Override selected facets from the URL (e.g. force a collection)."
		},
		"hideUnavailableItems": {
			"type": "boolean",
			"nullable": true,
			"title": "Hide Unavailable Items",
			"description": "Do not return out-of-stock items."
		}
	}
};
const s20: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Count"
		}
	}
};
const s21: BlockPropsSchema = {
	"type": "object",
	"additionalProperties": true
};
const s22: BlockPropsSchema = {
	"description": "Fetch a product details page using the legacy Catalog search API.",
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug"
		},
		"skuId": {
			"type": "string",
			"nullable": true,
			"title": "SkuId"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		},
		"includeOriginalAttributes": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "IncludeOriginalAttributes"
		},
		"preferDescription": {
			"type": "boolean",
			"nullable": true,
			"title": "PreferDescription"
		},
		"indexingSkus": {
			"type": "boolean",
			"nullable": true,
			"description": "When true, pages with ?skuId are still indexable",
			"title": "IndexingSkus"
		}
	},
	"required": [
		"slug"
	]
};
const s23: BlockPropsSchema = {
	"description": "Fetch a product list using the legacy Catalog search API.",
	"type": "object",
	"properties": {
		"query": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"collection": {
							"type": "string",
							"title": "Collection"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"collection",
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"term": {
							"type": "string",
							"nullable": true,
							"title": "Term"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"fq": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "Fq"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"fq",
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"skuIds": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "SkuIds"
						}
					},
					"required": [
						"skuIds"
					]
				},
				{
					"type": "object",
					"properties": {
						"productIds": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "ProductIds"
						}
					},
					"required": [
						"productIds"
					]
				}
			],
			"title": "Query"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		}
	},
	"required": [
		"query"
	]
};
const s24: BlockPropsSchema = {
	"description": "Fetch a product listing page (PLP) using the legacy Catalog search API.\nHandles categories, departments, brands, collections, and full-text search.",
	"type": "object",
	"properties": {
		"url": {
			"type": "object",
			"hide": "true",
			"nullable": true,
			"description": "URL of the page being rendered (used for filter links, pagination, etc.). Defaults to __pageUrl.",
			"title": "Url"
		},
		"term": {
			"type": "string",
			"nullable": true,
			"description": "Override the search term (path). Defaults to url.pathname",
			"title": "Term"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"description": "Items per page",
			"title": "Count"
		},
		"page": {
			"type": "number",
			"nullable": true,
			"description": "Current page number (0-indexed internally; see pageOffset)",
			"title": "Page"
		},
		"pageOffset": {
			"type": "number",
			"nullable": true,
			"description": "Starting page offset. Defaults to 1.",
			"title": "PageOffset"
		},
		"sort": {
			"type": "string",
			"enum": [
				"",
				"OrderByTopSaleDESC",
				"OrderByReleaseDateDESC",
				"OrderByBestDiscountDESC",
				"OrderByPriceDESC",
				"OrderByPriceASC",
				"OrderByNameASC",
				"OrderByNameDESC",
				"OrderByScoreDESC",
				"OrderByReviewRateDESC"
			],
			"nullable": true,
			"title": "Sort"
		},
		"ft": {
			"type": "string",
			"nullable": true,
			"description": "FullText search term",
			"title": "Ft"
		},
		"fq": {
			"type": "string",
			"nullable": true,
			"description": "Filter query",
			"title": "Fq"
		},
		"map": {
			"type": "string",
			"nullable": true,
			"description": "Map parameter",
			"title": "Map"
		},
		"filters": {
			"type": "string",
			"enum": [
				"dynamic",
				"static"
			],
			"nullable": true,
			"description": "Filter behavior: dynamic (default) or static",
			"title": "Filters"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL origin.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		},
		"useCollectionName": {
			"type": "boolean",
			"nullable": true,
			"description": "Use collection name as page title",
			"title": "UseCollectionName"
		},
		"ignoreCaseSelected": {
			"type": "boolean",
			"nullable": true,
			"description": "Ignore case when checking if a facet is selected",
			"title": "IgnoreCaseSelected"
		},
		"includeOriginalAttributes": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "IncludeOriginalAttributes"
		}
	}
};
const s25: BlockPropsSchema = {
	"description": "Fetch legacy autocomplete/search suggestions.",
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"description": "Max results. Defaults to 4.",
			"title": "Count"
		}
	}
};
const s26: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"title": "Slug"
		},
		"skuId": {
			"type": "string",
			"nullable": true,
			"title": "SkuId"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		},
		"includeOriginalAttributes": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "IncludeOriginalAttributes"
		},
		"preferDescription": {
			"type": "boolean",
			"nullable": true,
			"title": "PreferDescription"
		},
		"indexingSkus": {
			"type": "boolean",
			"nullable": true,
			"description": "When true, pages with ?skuId are still indexable",
			"title": "IndexingSkus"
		}
	},
	"required": [
		"slug"
	]
};
const s27: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"query": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"collection": {
							"type": "string",
							"title": "Collection"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"collection",
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"term": {
							"type": "string",
							"nullable": true,
							"title": "Term"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"fq": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "Fq"
						},
						"count": {
							"type": "number",
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"enum": [
								"",
								"OrderByTopSaleDESC",
								"OrderByReleaseDateDESC",
								"OrderByBestDiscountDESC",
								"OrderByPriceDESC",
								"OrderByPriceASC",
								"OrderByNameASC",
								"OrderByNameDESC",
								"OrderByScoreDESC",
								"OrderByReviewRateDESC"
							],
							"nullable": true,
							"title": "Sort"
						}
					},
					"required": [
						"fq",
						"count"
					]
				},
				{
					"type": "object",
					"properties": {
						"skuIds": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "SkuIds"
						}
					},
					"required": [
						"skuIds"
					]
				},
				{
					"type": "object",
					"properties": {
						"productIds": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "ProductIds"
						}
					},
					"required": [
						"productIds"
					]
				}
			],
			"title": "Query"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		}
	},
	"required": [
		"query"
	]
};
const s28: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"url": {
			"type": "object",
			"hide": "true",
			"nullable": true,
			"description": "URL of the page being rendered (used for filter links, pagination, etc.). Defaults to __pageUrl.",
			"title": "Url"
		},
		"term": {
			"type": "string",
			"nullable": true,
			"description": "Override the search term (path). Defaults to url.pathname",
			"title": "Term"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"description": "Items per page",
			"title": "Count"
		},
		"page": {
			"type": "number",
			"nullable": true,
			"description": "Current page number (0-indexed internally; see pageOffset)",
			"title": "Page"
		},
		"pageOffset": {
			"type": "number",
			"nullable": true,
			"description": "Starting page offset. Defaults to 1.",
			"title": "PageOffset"
		},
		"sort": {
			"type": "string",
			"enum": [
				"",
				"OrderByTopSaleDESC",
				"OrderByReleaseDateDESC",
				"OrderByBestDiscountDESC",
				"OrderByPriceDESC",
				"OrderByPriceASC",
				"OrderByNameASC",
				"OrderByNameDESC",
				"OrderByScoreDESC",
				"OrderByReviewRateDESC"
			],
			"nullable": true,
			"title": "Sort"
		},
		"ft": {
			"type": "string",
			"nullable": true,
			"description": "FullText search term",
			"title": "Ft"
		},
		"fq": {
			"type": "string",
			"nullable": true,
			"description": "Filter query",
			"title": "Fq"
		},
		"map": {
			"type": "string",
			"nullable": true,
			"description": "Map parameter",
			"title": "Map"
		},
		"filters": {
			"type": "string",
			"enum": [
				"dynamic",
				"static"
			],
			"nullable": true,
			"description": "Filter behavior: dynamic (default) or static",
			"title": "Filters"
		},
		"baseUrl": {
			"type": "string",
			"nullable": true,
			"description": "Base URL for building canonical/absolute links. Defaults to the page URL origin.",
			"title": "BaseUrl"
		},
		"priceCurrency": {
			"type": "string",
			"nullable": true,
			"title": "PriceCurrency"
		},
		"useCollectionName": {
			"type": "boolean",
			"nullable": true,
			"description": "Use collection name as page title",
			"title": "UseCollectionName"
		},
		"ignoreCaseSelected": {
			"type": "boolean",
			"nullable": true,
			"description": "Ignore case when checking if a facet is selected",
			"title": "IgnoreCaseSelected"
		},
		"includeOriginalAttributes": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "IncludeOriginalAttributes"
		}
	}
};
const s29: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"slug": {
			"type": "string",
			"nullable": true,
			"title": "Slug"
		},
		"productId": {
			"type": "string",
			"nullable": true,
			"title": "ProductId"
		},
		"crossSelling": {
			"type": "string",
			"enum": [
				"similars",
				"suggestions",
				"accessories",
				"whosawalsosaw",
				"whosawalsobought",
				"whoboughtalsobought",
				"showtogether"
			],
			"nullable": true,
			"title": "CrossSelling"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Count"
		},
		"hideUnavailableItems": {
			"type": "boolean",
			"nullable": true,
			"title": "HideUnavailableItems"
		}
	}
};
const s30: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"description": "Max results. Defaults to 4.",
			"title": "Count"
		}
	}
};
const s31: BlockPropsSchema = {
	"description": "Get a single sales channel by ID (public API).",
	"type": "object",
	"additionalProperties": true
};
const s32: BlockPropsSchema = {
	"description": "List all configured pickup points (private API — requires appKey/appToken).",
	"type": "object",
	"properties": {}
};
const s33: BlockPropsSchema = {
	"description": "Search pickup points near a geographic location (public API).\nPass either `geoCoordinates` (lon/lat array) **or** `postalCode` + `countryCode`.",
	"type": "object",
	"properties": {
		"geoCoordinates": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"nullable": true,
			"title": "GeoCoordinates"
		},
		"postalCode": {
			"type": "string",
			"nullable": true,
			"title": "PostalCode"
		},
		"countryCode": {
			"type": "string",
			"nullable": true,
			"title": "CountryCode"
		}
	}
};
const s34: BlockPropsSchema = {
	"description": "List all sales channels (private API — requires appKey/appToken).",
	"type": "object",
	"properties": {}
};
const s35: BlockPropsSchema = {
	"description": "List inventory balances for a SKU across all warehouses.",
	"type": "object",
	"additionalProperties": true
};
const s36: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"freeShippingTarget": {
			"type": "number",
			"nullable": true,
			"description": "Free-shipping threshold in major units. `0` disables the progress bar.",
			"title": "FreeShippingTarget"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"description": "Override the OrderForm's locale (BCP-47, e.g. `\"pt-BR\"`).",
			"title": "Locale"
		},
		"checkoutHref": {
			"type": "string",
			"nullable": true,
			"description": "Where the checkout button sends the user. Default: `/checkout`.",
			"title": "CheckoutHref"
		},
		"enableCoupon": {
			"type": "boolean",
			"nullable": true,
			"description": "Whether the UI should expose the coupon input. Default: `true`.",
			"title": "EnableCoupon"
		}
	}
};
const s37: BlockPropsSchema = {
	"description": "Fetch the category tree and transform it into an array of\n`SiteNavigationElement` nodes suitable for navigation menus.",
	"type": "object",
	"additionalProperties": true
};
const s38: BlockPropsSchema = {
	"description": "Fetch a single user order by its ID.\nThe user must be authenticated or the caller must have OMS permissions.",
	"type": "object",
	"additionalProperties": true
};
const s39: BlockPropsSchema = {
	"description": "Fetch order details for the order-placed / confirmation page.\n\nAccepts either:\n - An **order group ID** (no hyphen) → returns all orders in the group\n - A single **order ID** (contains hyphen) → returns that order wrapped in an array\n\nThe caller must supply an `authCookie` containing at least the\nVtexIdclientAutCookie, CheckoutDataAccess, and Vtex_CHKO_Auth cookies\nthat VTEX sets after checkout.\n\nPorted from deco-cx/apps:\n  vtex/loaders/orderplaced.ts",
	"type": "object",
	"additionalProperties": true
};
const s40: BlockPropsSchema = {
	"description": "List orders for a given client e-mail.\nThe user must be authenticated or the caller must have OMS permissions.",
	"type": "object",
	"properties": {
		"clientEmail": {
			"type": "string",
			"title": "ClientEmail"
		},
		"page": {
			"type": "string",
			"nullable": true,
			"title": "Page"
		},
		"perPage": {
			"type": "string",
			"nullable": true,
			"title": "PerPage"
		}
	},
	"required": [
		"clientEmail"
	]
};
const s41: BlockPropsSchema = {
	"description": "Resolve a URL path to a VTEX page type.",
	"type": "object",
	"additionalProperties": true
};
const s42: BlockPropsSchema = {
	"description": "List available payment systems for the authenticated user.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s43: BlockPropsSchema = {
	"description": "List saved payment methods for the authenticated user.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s44: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"props": {
			"anyOf": [
				{
					"type": "object",
					"properties": {
						"collection": {
							"type": "string",
							"description": "VTEX product cluster id (e.g. `\"150\"`).",
							"title": "Collection"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"collection"
					],
					"title": "Collection ID"
				},
				{
					"type": "object",
					"properties": {
						"query": {
							"type": "string",
							"title": "Query"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"fuzzy": {
							"type": "string",
							"nullable": true,
							"description": "Pass either a raw IS fuzzy value (`\"0\" | \"1\" | \"auto\"`) or call `mapLabelledFuzzyToFuzzy()`.",
							"title": "Fuzzy"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"query"
					],
					"title": "Keyword Search"
				},
				{
					"type": "object",
					"properties": {
						"ids": {
							"type": "array",
							"items": {
								"type": "string"
							},
							"title": "Ids"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"ids"
					],
					"title": "Product IDs"
				},
				{
					"type": "object",
					"properties": {
						"query": {
							"type": "string",
							"nullable": true,
							"title": "Query"
						},
						"facets": {
							"type": "string",
							"description": "Facets path (e.g. `category-1/moda-feminina/category-2/calcados`).",
							"title": "Facets"
						},
						"count": {
							"type": "number",
							"nullable": true,
							"title": "Count"
						},
						"sort": {
							"type": "string",
							"nullable": true,
							"title": "Sort"
						},
						"hideUnavailableItems": {
							"type": "boolean",
							"nullable": true,
							"title": "HideUnavailableItems"
						}
					},
					"required": [
						"facets"
					],
					"title": "Advanced Facets"
				}
			],
			"nullable": true,
			"title": "Props"
		}
	}
};
const s45: BlockPropsSchema = {
	"description": "Fetch the full profile for the currently authenticated user.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s46: BlockPropsSchema = {
	"description": "Fetch a checkout profile by e-mail.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s47: BlockPropsSchema = {
	"description": "Fetch a promotion / calculator-configuration by its ID.\n\nNote: uses the **pvt** (private) endpoint — requires appKey/appToken\nor a valid authentication cookie.",
	"type": "object",
	"additionalProperties": true
};
const s48: BlockPropsSchema = {
	"description": "Search for products by free-text term and return a list of\n`{ value (SKU ID), label, image }` options.\n\nHits the IS autocomplete_suggestions endpoint.",
	"type": "object",
	"additionalProperties": true
};
const s49: BlockPropsSchema = {
	"description": "Fetch the top searches from Intelligent Search.",
	"type": "object",
	"additionalProperties": true
};
const s50: BlockPropsSchema = {
	"description": "Validate whether a product search returns results.\n\nRuns the given search parameters against Intelligent Search.\nIf no results are found and the props include facets, retries\nthe search without facets.\n\nReturns the raw IS response or `null` when nothing is found.",
	"type": "object",
	"properties": {
		"query": {
			"type": "string",
			"nullable": true,
			"title": "Query"
		},
		"facets": {
			"type": "string",
			"nullable": true,
			"title": "Facets"
		},
		"sort": {
			"type": "string",
			"nullable": true,
			"title": "Sort"
		},
		"count": {
			"type": "number",
			"nullable": true,
			"title": "Count"
		},
		"page": {
			"type": "number",
			"nullable": true,
			"title": "Page"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"title": "Locale"
		}
	}
};
const s51: BlockPropsSchema = {
	"description": "Fetch the current session data.",
	"type": "object",
	"additionalProperties": true
};
const s52: BlockPropsSchema = {
	"description": "Fetch all active login sessions for the currently authenticated user.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s53: BlockPropsSchema = {
	"description": "Fetch the authenticated user as a Schema.org-style `Person`.\nReturns `null` when no valid session exists or the query fails.",
	"type": "object",
	"additionalProperties": true
};
const s54: BlockPropsSchema = {
	"description": "Fetch the wishlist for a given shopper.\nRequires a valid VTEX auth cookie.",
	"type": "object",
	"additionalProperties": true
};
const s55: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"count": {
			"type": "number",
			"nullable": true,
			"description": "Items per page",
			"default": 12,
			"title": "Count"
		},
		"offset": {
			"type": "number",
			"enum": [
				0,
				1
			],
			"nullable": true,
			"description": "1 to start from index 1",
			"default": 0,
			"title": "Offset"
		},
		"authCookie": {
			"type": "string",
			"description": "The user's auth cookie string",
			"title": "AuthCookie"
		},
		"shopperId": {
			"type": "string",
			"description": "The user's shopper ID (email)",
			"title": "ShopperId"
		},
		"url": {
			"type": "string",
			"description": "Current page URL (for pagination links)",
			"title": "Url"
		}
	},
	"required": [
		"authCookie",
		"shopperId",
		"url"
	]
};
const s56: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"props": {
			"type": "object",
			"properties": {
				"query": {
					"type": "string",
					"nullable": true,
					"title": "Query"
				},
				"count": {
					"type": "number",
					"nullable": true,
					"title": "Count"
				},
				"sort": {
					"type": "string",
					"nullable": true,
					"title": "Sort"
				},
				"collection": {
					"type": "string",
					"nullable": true,
					"title": "Collection"
				}
			},
			"nullable": true,
			"title": "Props"
		},
		"page": {
			"type": "number",
			"nullable": true,
			"title": "Page"
		},
		"pagesize": {
			"type": "number",
			"nullable": true,
			"title": "Pagesize"
		}
	}
};
const s57: BlockPropsSchema = {
	"description": "Transform a single VTEX SKU (via private Catalog API) into a commerce Product.\n\nFetches the SKU details, all sibling SKUs for the same product, sales channels,\nand runs checkout simulation for each seller to build offer data.\n\nPorted from: vtex/loaders/workflow/product.ts",
	"type": "object",
	"properties": {
		"productID": {
			"type": "string",
			"description": "The SKU ID (stockKeepingUnitId) to load",
			"title": "ProductID"
		},
		"salesChannel": {
			"type": "number",
			"nullable": true,
			"description": "Sales channel for simulation. Defaults to 1.",
			"title": "SalesChannel"
		}
	},
	"required": [
		"productID"
	]
};
const s58: BlockPropsSchema = {
	"description": "Fetch a page of SKU IDs and return minimal Product stubs.\nUse in batch workflows to enumerate the catalog; call workflowProduct\nfor each ID if full details are needed.\n\nPorted from: vtex/loaders/workflow/products.ts",
	"type": "object",
	"properties": {
		"page": {
			"type": "number",
			"title": "Page"
		},
		"pagesize": {
			"type": "number",
			"title": "Pagesize"
		}
	},
	"required": [
		"page",
		"pagesize"
	]
};
const s59: BlockPropsSchema = {
	"description": "Create a new user address. Requires the user's VtexIdclientAutCookie token.",
	"type": "object",
	"properties": {
		"addressName": {
			"type": "string",
			"title": "AddressName"
		},
		"addressType": {
			"type": "string",
			"nullable": true,
			"title": "AddressType"
		},
		"city": {
			"type": "string",
			"nullable": true,
			"title": "City"
		},
		"complement": {
			"type": "string",
			"nullable": true,
			"title": "Complement"
		},
		"country": {
			"type": "string",
			"nullable": true,
			"title": "Country"
		},
		"geoCoordinates": {
			"type": "array",
			"items": {
				"type": "number"
			},
			"nullable": true,
			"title": "GeoCoordinates"
		},
		"neighborhood": {
			"type": "string",
			"nullable": true,
			"title": "Neighborhood"
		},
		"number": {
			"type": "string",
			"nullable": true,
			"title": "Number"
		},
		"postalCode": {
			"type": "string",
			"nullable": true,
			"title": "PostalCode"
		},
		"receiverName": {
			"type": "string",
			"nullable": true,
			"title": "ReceiverName"
		},
		"reference": {
			"type": "string",
			"nullable": true,
			"title": "Reference"
		},
		"state": {
			"type": "string",
			"nullable": true,
			"title": "State"
		},
		"street": {
			"type": "string",
			"nullable": true,
			"title": "Street"
		}
	},
	"required": [
		"addressName"
	]
};
const s60: BlockPropsSchema = {
	"description": "Delete an address by its ID. Returns remaining addresses.",
	"type": "object",
	"additionalProperties": true
};
const s61: BlockPropsSchema = {
	"description": "Update an existing address. Returns the updated address.",
	"type": "object",
	"additionalProperties": true
};
const s62: BlockPropsSchema = {
	"description": "Passwordless sign-in via email access key.",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"accessKey": {
			"type": "string",
			"title": "AccessKey"
		},
		"authenticationToken": {
			"type": "string",
			"title": "AuthenticationToken"
		}
	},
	"required": [
		"email",
		"accessKey",
		"authenticationToken"
	]
};
const s63: BlockPropsSchema = {
	"description": "Classic email + password sign-in.\nCalls startAuthentication internally if no authenticationToken provided.\nSet-Cookie headers from both calls are forwarded via RequestContext.responseHeaders.",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"password": {
			"type": "string",
			"title": "Password"
		},
		"authenticationToken": {
			"type": "string",
			"nullable": true,
			"title": "AuthenticationToken"
		}
	},
	"required": [
		"email",
		"password"
	]
};
const s64: BlockPropsSchema = {
	"description": "Extract login cookies from an AuthResponse.\nReturns null if auth failed.",
	"type": "object",
	"properties": {
		"authStatus": {
			"type": "string",
			"title": "AuthStatus"
		},
		"promptMFA": {
			"type": "boolean",
			"title": "PromptMFA"
		},
		"clientToken": {
			"type": "string",
			"nullable": true,
			"title": "ClientToken"
		},
		"authCookie": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string",
					"title": "Name"
				},
				"Value": {
					"type": "string",
					"title": "Value"
				}
			},
			"required": [
				"Name",
				"Value"
			],
			"nullable": true,
			"title": "AuthCookie"
		},
		"accountAuthCookie": {
			"type": "object",
			"properties": {
				"Name": {
					"type": "string",
					"title": "Name"
				},
				"Value": {
					"type": "string",
					"title": "Value"
				}
			},
			"required": [
				"Name",
				"Value"
			],
			"nullable": true,
			"title": "AccountAuthCookie"
		},
		"expiresIn": {
			"type": "number",
			"title": "ExpiresIn"
		},
		"userId": {
			"type": "string",
			"nullable": true,
			"title": "UserId"
		},
		"phoneNumber": {
			"type": "string",
			"nullable": true,
			"title": "PhoneNumber"
		},
		"scope": {
			"type": "string",
			"nullable": true,
			"title": "Scope"
		}
	},
	"required": [
		"authStatus",
		"promptMFA",
		"clientToken",
		"authCookie",
		"accountAuthCookie",
		"expiresIn",
		"userId",
		"phoneNumber",
		"scope"
	]
};
const s65: BlockPropsSchema = {
	"description": "Logout — returns list of cookie names that must be cleared (Max-Age=0).",
	"type": "object",
	"properties": {}
};
const s66: BlockPropsSchema = {
	"description": "Sets a new password using an email access key (password-recovery flow).",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"newPassword": {
			"type": "string",
			"title": "NewPassword"
		},
		"accessKey": {
			"type": "string",
			"title": "AccessKey"
		},
		"authenticationToken": {
			"type": "string",
			"title": "AuthenticationToken"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"title": "Locale"
		}
	},
	"required": [
		"email",
		"newPassword",
		"accessKey",
		"authenticationToken"
	]
};
const s67: BlockPropsSchema = {
	"description": "Refreshes the VTEX auth token using existing session cookies.\nCookies are read automatically from RequestContext.",
	"type": "object",
	"properties": {
		"fingerprint": {
			"type": "string",
			"nullable": true,
			"title": "Fingerprint"
		}
	},
	"nullable": true
};
const s68: BlockPropsSchema = {
	"description": "Resets password for an already-authenticated user.\nCalls startAuthentication internally if no authenticationToken provided.\nSet-Cookie headers from both calls are forwarded via RequestContext.responseHeaders.",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"currentPassword": {
			"type": "string",
			"title": "CurrentPassword"
		},
		"newPassword": {
			"type": "string",
			"title": "NewPassword"
		},
		"authenticationToken": {
			"type": "string",
			"nullable": true,
			"title": "AuthenticationToken"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"title": "Locale"
		}
	},
	"required": [
		"email",
		"currentPassword",
		"newPassword"
	]
};
const s69: BlockPropsSchema = {
	"description": "Sends an access-key verification email.\nCalls startAuthentication internally if no authenticationToken provided.\nReturns { success, authenticationToken }.",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"authenticationToken": {
			"type": "string",
			"nullable": true,
			"title": "AuthenticationToken"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"title": "Locale"
		},
		"parentAppId": {
			"type": "string",
			"nullable": true,
			"title": "ParentAppId"
		}
	},
	"required": [
		"email"
	]
};
const s70: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"callbackUrl": {
			"type": "string",
			"nullable": true,
			"title": "CallbackUrl"
		},
		"returnUrl": {
			"type": "string",
			"nullable": true,
			"title": "ReturnUrl"
		},
		"locale": {
			"type": "string",
			"nullable": true,
			"title": "Locale"
		},
		"appStart": {
			"type": "boolean",
			"nullable": true,
			"title": "AppStart"
		}
	},
	"nullable": true
};
const s71: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"text": {
			"type": "string",
			"title": "Text"
		}
	},
	"required": [
		"orderFormId",
		"text"
	]
};
const s72: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"orderItems": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"title": "Id"
					},
					"seller": {
						"type": "string",
						"title": "Seller"
					},
					"quantity": {
						"type": "number",
						"title": "Quantity"
					},
					"index": {
						"type": "number",
						"nullable": true,
						"title": "Index"
					},
					"price": {
						"type": "number",
						"nullable": true,
						"title": "Price"
					}
				},
				"required": [
					"id",
					"seller",
					"quantity"
				]
			},
			"title": "OrderItems"
		},
		"allowedOutdatedData": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "AllowedOutdatedData"
		}
	},
	"required": [
		"orderFormId",
		"orderItems"
	]
};
const s73: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"itemIndex": {
			"type": "number",
			"title": "ItemIndex"
		},
		"offeringId": {
			"anyOf": [
				{
					"type": "string"
				},
				{
					"type": "number"
				}
			],
			"title": "OfferingId"
		},
		"expectedOrderFormSections": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "ExpectedOrderFormSections"
		}
	},
	"required": [
		"orderFormId",
		"itemIndex",
		"offeringId"
	]
};
const s74: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		}
	},
	"required": [
		"orderFormId"
	]
};
const s75: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"paymentSystem": {
			"type": "number",
			"title": "PaymentSystem"
		}
	},
	"required": [
		"orderFormId",
		"paymentSystem"
	]
};
const s76: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"nullable": true,
			"title": "OrderFormId"
		}
	}
};
const s77: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"postalCode": {
			"type": "string",
			"title": "PostalCode"
		},
		"salesChannel": {
			"type": "string",
			"nullable": true,
			"title": "SalesChannel"
		}
	},
	"required": [
		"postalCode"
	]
};
const s78: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"itemIndex": {
			"type": "number",
			"title": "ItemIndex"
		},
		"attachment": {
			"type": "string",
			"title": "Attachment"
		},
		"content": {
			"type": "object",
			"additionalProperties": {},
			"title": "Content"
		},
		"noSplitItem": {
			"type": "boolean",
			"nullable": true,
			"title": "NoSplitItem"
		},
		"expectedOrderFormSections": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "ExpectedOrderFormSections"
		}
	},
	"required": [
		"orderFormId",
		"itemIndex",
		"attachment",
		"content"
	]
};
const s79: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"postalCode": {
			"type": "string",
			"title": "PostalCode"
		},
		"country": {
			"type": "string",
			"nullable": true,
			"title": "Country"
		}
	},
	"required": [
		"orderFormId",
		"postalCode"
	]
};
const s80: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"items": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"type": "number"
							}
						],
						"title": "Id"
					},
					"quantity": {
						"type": "number",
						"title": "Quantity"
					},
					"seller": {
						"type": "string",
						"title": "Seller"
					}
				},
				"required": [
					"id",
					"quantity",
					"seller"
				]
			},
			"title": "Items"
		},
		"postalCode": {
			"type": "string",
			"title": "PostalCode"
		},
		"country": {
			"type": "string",
			"nullable": true,
			"title": "Country"
		},
		"RnbBehavior": {
			"type": "number",
			"enum": [
				0,
				1
			],
			"nullable": true,
			"title": "RnbBehavior"
		}
	},
	"required": [
		"items",
		"postalCode"
	]
};
const s81: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"orderItems": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"index": {
						"type": "number",
						"title": "Index"
					},
					"quantity": {
						"type": "number",
						"title": "Quantity"
					}
				},
				"required": [
					"index",
					"quantity"
				]
			},
			"title": "OrderItems"
		},
		"allowedOutdatedData": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "AllowedOutdatedData"
		},
		"noSplitItem": {
			"type": "boolean",
			"nullable": true,
			"title": "NoSplitItem"
		}
	},
	"required": [
		"orderFormId",
		"orderItems"
	]
};
const s82: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"itemIndex": {
			"type": "number",
			"title": "ItemIndex"
		},
		"price": {
			"type": "number",
			"title": "Price"
		}
	},
	"required": [
		"orderFormId",
		"itemIndex",
		"price"
	]
};
const s83: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"attachment": {
			"type": "string",
			"title": "Attachment"
		},
		"body": {
			"type": "object",
			"additionalProperties": {},
			"title": "Body"
		},
		"expectedOrderFormSections": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "ExpectedOrderFormSections"
		}
	},
	"required": [
		"orderFormId",
		"attachment",
		"body"
	]
};
const s84: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"fields": {
			"type": "object",
			"additionalProperties": {},
			"title": "Fields"
		},
		"ignoreProfileData": {
			"type": "boolean",
			"nullable": true,
			"title": "IgnoreProfileData"
		}
	},
	"required": [
		"orderFormId",
		"fields"
	]
};
const s85: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"orderFormId": {
			"type": "string",
			"title": "OrderFormId"
		},
		"giftId": {
			"type": "string",
			"title": "GiftId"
		},
		"selectedGifts": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"title": "Id"
					},
					"seller": {
						"type": "string",
						"title": "Seller"
					},
					"quantity": {
						"type": "number",
						"title": "Quantity"
					}
				},
				"required": [
					"id",
					"seller",
					"quantity"
				]
			},
			"title": "SelectedGifts"
		},
		"expectedOrderFormSections": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"nullable": true,
			"title": "ExpectedOrderFormSections"
		}
	},
	"required": [
		"orderFormId",
		"giftId",
		"selectedGifts"
	]
};
const s86: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"entity": {
			"type": "string",
			"title": "Entity"
		},
		"data": {
			"type": "object",
			"additionalProperties": {},
			"title": "Data"
		}
	},
	"required": [
		"entity",
		"data"
	]
};
const s87: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"entity": {
			"type": "string",
			"title": "Entity"
		},
		"documentId": {
			"type": "string",
			"title": "DocumentId"
		}
	},
	"required": [
		"entity",
		"documentId"
	]
};
const s88: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"entity": {
			"type": "string",
			"title": "Entity"
		},
		"documentId": {
			"type": "string",
			"title": "DocumentId"
		},
		"data": {
			"type": "object",
			"additionalProperties": {},
			"title": "Data"
		}
	},
	"required": [
		"entity",
		"documentId",
		"data"
	]
};
const s89: BlockPropsSchema = {
	"description": "Simple search — kept for backward compat.",
	"type": "object",
	"properties": {
		"entity": {
			"type": "string",
			"title": "Entity"
		},
		"filter": {
			"type": "string",
			"title": "Filter"
		}
	},
	"required": [
		"entity",
		"filter"
	]
};
const s90: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"acronym": {
			"type": "string",
			"title": "Acronym"
		},
		"fields": {
			"type": "string",
			"nullable": true,
			"title": "Fields"
		},
		"where": {
			"type": "string",
			"nullable": true,
			"title": "Where"
		},
		"sort": {
			"type": "string",
			"nullable": true,
			"title": "Sort"
		},
		"take": {
			"type": "number",
			"nullable": true,
			"default": "10 (max 100)",
			"title": "Take"
		},
		"skip": {
			"type": "number",
			"nullable": true,
			"default": 0,
			"title": "Skip"
		}
	},
	"required": [
		"acronym"
	],
	"description": "Full MasterData search with pagination, field selection, and sorting.\nPorted from deco-cx/apps vtex/loaders/masterdata/searchDocuments.ts",
	"see": "://developers.vtex.com/docs/api-reference/masterdata-api#get-/api/dataentities/-acronym-/search"
};
const s91: BlockPropsSchema = {
	"description": "Upload a file attachment to a MasterData document.\nUses the VTEX MasterData attachment API with appKey/appToken auth.",
	"type": "object",
	"properties": {
		"entity": {
			"type": "string",
			"title": "Entity"
		},
		"documentId": {
			"type": "string",
			"title": "DocumentId"
		},
		"field": {
			"type": "string",
			"title": "Field"
		},
		"fileName": {
			"type": "string",
			"title": "FileName"
		},
		"fileBase64": {
			"type": "string",
			"description": "Base64-encoded file content",
			"title": "FileBase64"
		},
		"contentType": {
			"type": "string",
			"title": "ContentType"
		}
	},
	"required": [
		"entity",
		"documentId",
		"field",
		"fileName",
		"fileBase64",
		"contentType"
	]
};
const s92: BlockPropsSchema = {
	"description": "Delete a saved payment token (credit card) for the authenticated user.\nUses the my-cards-graphql VTEX IO app.",
	"type": "object",
	"additionalProperties": true
};
const s93: BlockPropsSchema = {
	"description": "Register a \"notify me when back in stock\" request.\nUses the legacy VTEX .aspx form endpoint (FormData, not JSON).",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"skuId": {
			"type": "string",
			"title": "SkuId"
		},
		"name": {
			"type": "string",
			"nullable": true,
			"title": "Name"
		}
	},
	"required": [
		"email",
		"skuId"
	]
};
const s94: BlockPropsSchema = {
	"description": "Send an Intelligent Search analytics event to sp.vtex.com.",
	"type": "object",
	"additionalProperties": true
};
const s95: BlockPropsSchema = {
	"description": "Submit a product review via the Reviews & Ratings API.\nHits POST https://{account}.myvtex.com/reviews-and-ratings/api/review.\nAuth is passed via the `VtexIdclientAutCookie` header (not a Cookie header).",
	"type": "object",
	"properties": {
		"productId": {
			"type": "string",
			"title": "ProductId"
		},
		"rating": {
			"type": "number",
			"title": "Rating"
		},
		"title": {
			"type": "string",
			"title": "Title"
		},
		"text": {
			"type": "string",
			"title": "Text"
		},
		"reviewerName": {
			"type": "string",
			"title": "ReviewerName"
		},
		"approved": {
			"type": "boolean",
			"title": "Approved"
		}
	},
	"required": [
		"productId",
		"rating",
		"title",
		"text",
		"reviewerName",
		"approved"
	]
};
const s96: BlockPropsSchema = {
	"description": "Subscribe to the newsletter via the legacy VTEX .aspx form endpoint.\nUses raw fetch because the body is FormData (not JSON).",
	"type": "object",
	"properties": {
		"email": {
			"type": "string",
			"title": "Email"
		},
		"name": {
			"type": "string",
			"nullable": true,
			"title": "Name"
		},
		"page": {
			"type": "string",
			"nullable": true,
			"title": "Page"
		},
		"part": {
			"type": "string",
			"nullable": true,
			"title": "Part"
		},
		"campaing": {
			"type": "string",
			"nullable": true,
			"description": "Intentionally preserving the original typo from the VTEX legacy form field.",
			"title": "Campaing"
		}
	},
	"required": [
		"email"
	]
};
const s97: BlockPropsSchema = {
	"description": "Toggle the newsletter opt-in flag for an authenticated user.\nThe original Deco action extracted `email` from the auth cookie payload.\nHere the caller must provide it explicitly.",
	"type": "object",
	"additionalProperties": true
};
const s98: BlockPropsSchema = {
	"description": "Cancel an order on behalf of the authenticated user.\nHits POST /api/checkout/pub/orders/{orderId}/user-cancel-request\non vtexcommercestable.com.br.",
	"type": "object",
	"additionalProperties": true
};
const s99: BlockPropsSchema = {
	"description": "Update user profile.\nThe original Deco action extracted `email` from the auth cookie payload.\nHere the caller must provide it explicitly.",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string",
			"nullable": true,
			"title": "FirstName"
		},
		"lastName": {
			"type": "string",
			"nullable": true,
			"title": "LastName"
		},
		"birthDate": {
			"type": "string",
			"nullable": true,
			"title": "BirthDate"
		},
		"gender": {
			"type": "string",
			"nullable": true,
			"title": "Gender"
		},
		"homePhone": {
			"type": "string",
			"nullable": true,
			"title": "HomePhone"
		},
		"businessPhone": {
			"type": "string",
			"nullable": true,
			"title": "BusinessPhone"
		},
		"document": {
			"type": "string",
			"nullable": true,
			"title": "Document"
		},
		"tradeName": {
			"type": "string",
			"nullable": true,
			"title": "TradeName"
		},
		"corporateName": {
			"type": "string",
			"nullable": true,
			"title": "CorporateName"
		},
		"corporateDocument": {
			"type": "string",
			"nullable": true,
			"title": "CorporateDocument"
		},
		"stateRegistration": {
			"type": "string",
			"nullable": true,
			"title": "StateRegistration"
		},
		"isCorporate": {
			"type": "boolean",
			"nullable": true,
			"title": "IsCorporate"
		}
	}
};
const s100: BlockPropsSchema = {
	"description": "Update user profile via VTEX IO GraphQL. Handles cookie extraction,\nbirthDate normalization, and undefined-key cleanup.",
	"type": "object",
	"additionalProperties": true
};
const s101: BlockPropsSchema = {
	"type": "object",
	"properties": {
		"data": {
			"type": "object",
			"additionalProperties": {},
			"title": "Data"
		}
	},
	"required": [
		"data"
	]
};
const s102: BlockPropsSchema = {
	"description": "Log out / delete a VTEX session via the store-graphql mutation.\nRequires a valid auth cookie.",
	"type": "object",
	"properties": {
		"sessionId": {
			"type": "string",
			"title": "SessionId"
		},
		"authCookie": {
			"type": "string",
			"title": "AuthCookie"
		}
	},
	"required": [
		"sessionId",
		"authCookie"
	]
};
const s103: BlockPropsSchema = {
	"description": "Edit the current VTEX session (public properties).",
	"type": "object",
	"properties": {
		"public": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"properties": {
					"value": {
						"type": "string",
						"title": "Value"
					}
				},
				"required": [
					"value"
				]
			},
			"title": "Public"
		}
	},
	"required": [
		"public"
	]
};
const s104: BlockPropsSchema = {
	"description": "Add an item to the user's wishlist.\nReturns the updated full wishlist.",
	"type": "object",
	"properties": {
		"productId": {
			"type": "string",
			"title": "ProductId"
		},
		"sku": {
			"type": "string",
			"title": "Sku"
		},
		"title": {
			"type": "string",
			"nullable": true,
			"title": "Title"
		}
	},
	"required": [
		"productId",
		"sku"
	]
};
const s105: BlockPropsSchema = {
	"description": "Remove an item from the user's wishlist by its list-entry ID.\nReturns the updated full wishlist.",
	"type": "object",
	"additionalProperties": true
};

export const loaderSchemas: Record<string, BlockPropsSchema> = {
	"vtex/loaders/ProductDetailsPage": s0,
	"vtex/loaders/ProductDetailsPage.ts": s0,
	"vtex/loaders/ProductList": s1,
	"vtex/loaders/ProductList.ts": s1,
	"vtex/loaders/ProductListingPage": s2,
	"vtex/loaders/ProductListingPage.ts": s2,
	"vtex/loaders/address/getAddressByPostalCode": s3,
	"vtex/loaders/address/getAddressByPostalCode.ts": s3,
	"vtex/loaders/address/getUserAddresses": s4,
	"vtex/loaders/address/getUserAddresses.ts": s4,
	"vtex/loaders/autocomplete/autocompleteSearch": s5,
	"vtex/loaders/autocomplete/autocompleteSearch.ts": s5,
	"vtex/loaders/brands/getBrandById": s6,
	"vtex/loaders/brands/getBrandById.ts": s6,
	"vtex/loaders/brands/listBrands": s7,
	"vtex/loaders/brands/listBrands.ts": s7,
	"vtex/loaders/cart/getCart": s8,
	"vtex/loaders/cart/getCart.ts": s8,
	"vtex/loaders/catalog/getBrands": s9,
	"vtex/loaders/catalog/getBrands.ts": s9,
	"vtex/loaders/catalog/getCategoryTree": s10,
	"vtex/loaders/catalog/getCategoryTree.ts": s10,
	"vtex/loaders/catalog/getCrossSelling": s11,
	"vtex/loaders/catalog/getCrossSelling.ts": s11,
	"vtex/loaders/catalog/getFacets": s12,
	"vtex/loaders/catalog/getFacets.ts": s12,
	"vtex/loaders/catalog/getPageType": s13,
	"vtex/loaders/catalog/getPageType.ts": s13,
	"vtex/loaders/catalog/getProductByIdOrSku": s14,
	"vtex/loaders/catalog/getProductByIdOrSku.ts": s14,
	"vtex/loaders/catalog/getProductSpecification": s15,
	"vtex/loaders/catalog/getProductSpecification.ts": s15,
	"vtex/loaders/catalog/getProductVariations": s16,
	"vtex/loaders/catalog/getProductVariations.ts": s16,
	"vtex/loaders/catalog/searchProducts": s17,
	"vtex/loaders/catalog/searchProducts.ts": s17,
	"vtex/loaders/collections/getCollections": s18,
	"vtex/loaders/collections/getCollections.ts": s18,
	"vtex/loaders/intelligentSearch/productDetailsPage": s0,
	"vtex/loaders/intelligentSearch/productDetailsPage.ts": s0,
	"vtex/loaders/intelligentSearch/productList": s1,
	"vtex/loaders/intelligentSearch/productList.ts": s1,
	"vtex/loaders/intelligentSearch/productListingPage": s19,
	"vtex/loaders/intelligentSearch/productListingPage.ts": s19,
	"vtex/loaders/intelligentSearch/suggestions": s20,
	"vtex/loaders/intelligentSearch/suggestions.ts": s20,
	"vtex/loaders/legacy/getFirstItemAvailable": s21,
	"vtex/loaders/legacy/getFirstItemAvailable.ts": s21,
	"vtex/loaders/legacy/legacyProductDetailsPage": s22,
	"vtex/loaders/legacy/legacyProductDetailsPage.ts": s22,
	"vtex/loaders/legacy/legacyProductList": s23,
	"vtex/loaders/legacy/legacyProductList.ts": s23,
	"vtex/loaders/legacy/legacyProductListingPage": s24,
	"vtex/loaders/legacy/legacyProductListingPage.ts": s24,
	"vtex/loaders/legacy/legacySuggestions": s25,
	"vtex/loaders/legacy/legacySuggestions.ts": s25,
	"vtex/loaders/legacy/productDetailsPage": s26,
	"vtex/loaders/legacy/productDetailsPage.ts": s26,
	"vtex/loaders/legacy/productList": s27,
	"vtex/loaders/legacy/productList.ts": s27,
	"vtex/loaders/legacy/productListingPage": s28,
	"vtex/loaders/legacy/productListingPage.ts": s28,
	"vtex/loaders/legacy/relatedProductsLoader": s29,
	"vtex/loaders/legacy/relatedProductsLoader.ts": s29,
	"vtex/loaders/legacy/suggestions": s30,
	"vtex/loaders/legacy/suggestions.ts": s30,
	"vtex/loaders/logistics/getSalesChannelById": s31,
	"vtex/loaders/logistics/getSalesChannelById.ts": s31,
	"vtex/loaders/logistics/listPickupPoints": s32,
	"vtex/loaders/logistics/listPickupPoints.ts": s32,
	"vtex/loaders/logistics/listPickupPointsByLocation": s33,
	"vtex/loaders/logistics/listPickupPointsByLocation.ts": s33,
	"vtex/loaders/logistics/listSalesChannels": s34,
	"vtex/loaders/logistics/listSalesChannels.ts": s34,
	"vtex/loaders/logistics/listStockByStore": s35,
	"vtex/loaders/logistics/listStockByStore.ts": s35,
	"vtex/loaders/minicart": s36,
	"vtex/loaders/minicart.ts": s36,
	"vtex/loaders/navbar/getNavbar": s37,
	"vtex/loaders/navbar/getNavbar.ts": s37,
	"vtex/loaders/orders/getOrderById": s38,
	"vtex/loaders/orders/getOrderById.ts": s38,
	"vtex/loaders/orders/getOrderPlaced": s39,
	"vtex/loaders/orders/getOrderPlaced.ts": s39,
	"vtex/loaders/orders/listOrders": s40,
	"vtex/loaders/orders/listOrders.ts": s40,
	"vtex/loaders/pageType/resolvePageType": s41,
	"vtex/loaders/pageType/resolvePageType.ts": s41,
	"vtex/loaders/payment/getPaymentSystems": s42,
	"vtex/loaders/payment/getPaymentSystems.ts": s42,
	"vtex/loaders/payment/getUserPayments": s43,
	"vtex/loaders/payment/getUserPayments.ts": s43,
	"vtex/loaders/productListFull": s44,
	"vtex/loaders/productListFull.ts": s44,
	"vtex/loaders/profile/getCurrentProfile": s45,
	"vtex/loaders/profile/getCurrentProfile.ts": s45,
	"vtex/loaders/profile/getProfileByEmail": s46,
	"vtex/loaders/profile/getProfileByEmail.ts": s46,
	"vtex/loaders/promotion/getPromotionById": s47,
	"vtex/loaders/promotion/getPromotionById.ts": s47,
	"vtex/loaders/search/getProductIdByTerm": s48,
	"vtex/loaders/search/getProductIdByTerm.ts": s48,
	"vtex/loaders/search/getTopSearches": s49,
	"vtex/loaders/search/getTopSearches.ts": s49,
	"vtex/loaders/search/validateProductSearch": s50,
	"vtex/loaders/search/validateProductSearch.ts": s50,
	"vtex/loaders/session/getSession": s51,
	"vtex/loaders/session/getSession.ts": s51,
	"vtex/loaders/session/getUserSessions": s52,
	"vtex/loaders/session/getUserSessions.ts": s52,
	"vtex/loaders/user/getUser": s53,
	"vtex/loaders/user/getUser.ts": s53,
	"vtex/loaders/wishlist/getWishlist": s54,
	"vtex/loaders/wishlist/getWishlist.ts": s54,
	"vtex/loaders/wishlistProducts/wishlistProducts": s55,
	"vtex/loaders/wishlistProducts/wishlistProducts.ts": s55,
	"vtex/loaders/workflow/products": s56,
	"vtex/loaders/workflow/products.ts": s56,
	"vtex/loaders/workflow/workflowProduct": s57,
	"vtex/loaders/workflow/workflowProduct.ts": s57,
	"vtex/loaders/workflow/workflowProducts": s58,
	"vtex/loaders/workflow/workflowProducts.ts": s58,
};

export const actionSchemas: Record<string, BlockPropsSchema> = {
	"vtex/actions/address/createAddress": s59,
	"vtex/actions/address/createAddress.ts": s59,
	"vtex/actions/address/createAddressFromRequest": s21,
	"vtex/actions/address/createAddressFromRequest.ts": s21,
	"vtex/actions/address/deleteAddress": s60,
	"vtex/actions/address/deleteAddress.ts": s60,
	"vtex/actions/address/deleteAddressFromRequest": s21,
	"vtex/actions/address/deleteAddressFromRequest.ts": s21,
	"vtex/actions/address/updateAddress": s61,
	"vtex/actions/address/updateAddress.ts": s61,
	"vtex/actions/address/updateAddressFromRequest": s21,
	"vtex/actions/address/updateAddressFromRequest.ts": s21,
	"vtex/actions/analytics/sendEvent": s21,
	"vtex/actions/analytics/sendEvent.ts": s21,
	"vtex/actions/auth/accessKeySignIn": s62,
	"vtex/actions/auth/accessKeySignIn.ts": s62,
	"vtex/actions/auth/classicSignIn": s63,
	"vtex/actions/auth/classicSignIn.ts": s63,
	"vtex/actions/auth/extractLoginCookies": s64,
	"vtex/actions/auth/extractLoginCookies.ts": s64,
	"vtex/actions/auth/logout": s65,
	"vtex/actions/auth/logout.ts": s65,
	"vtex/actions/auth/recoveryPassword": s66,
	"vtex/actions/auth/recoveryPassword.ts": s66,
	"vtex/actions/auth/refreshToken": s67,
	"vtex/actions/auth/refreshToken.ts": s67,
	"vtex/actions/auth/resetPassword": s68,
	"vtex/actions/auth/resetPassword.ts": s68,
	"vtex/actions/auth/sendEmailVerification": s69,
	"vtex/actions/auth/sendEmailVerification.ts": s69,
	"vtex/actions/auth/startAuthentication": s70,
	"vtex/actions/auth/startAuthentication.ts": s70,
	"vtex/actions/checkout/addCouponToCart": s71,
	"vtex/actions/checkout/addCouponToCart.ts": s71,
	"vtex/actions/checkout/addItemsToCart": s72,
	"vtex/actions/checkout/addItemsToCart.ts": s72,
	"vtex/actions/checkout/addOffering": s73,
	"vtex/actions/checkout/addOffering.ts": s73,
	"vtex/actions/checkout/changeToAnonymousUser": s74,
	"vtex/actions/checkout/changeToAnonymousUser.ts": s74,
	"vtex/actions/checkout/clearOrderFormMessages": s74,
	"vtex/actions/checkout/clearOrderFormMessages.ts": s74,
	"vtex/actions/checkout/getInstallments": s75,
	"vtex/actions/checkout/getInstallments.ts": s75,
	"vtex/actions/checkout/getOrCreateCart": s76,
	"vtex/actions/checkout/getOrCreateCart.ts": s76,
	"vtex/actions/checkout/getSellersByRegion": s77,
	"vtex/actions/checkout/getSellersByRegion.ts": s77,
	"vtex/actions/checkout/removeAllItems": s74,
	"vtex/actions/checkout/removeAllItems.ts": s74,
	"vtex/actions/checkout/removeItemAttachment": s78,
	"vtex/actions/checkout/removeItemAttachment.ts": s78,
	"vtex/actions/checkout/removeOffering": s73,
	"vtex/actions/checkout/removeOffering.ts": s73,
	"vtex/actions/checkout/setShippingPostalCode": s79,
	"vtex/actions/checkout/setShippingPostalCode.ts": s79,
	"vtex/actions/checkout/simulateCart": s80,
	"vtex/actions/checkout/simulateCart.ts": s80,
	"vtex/actions/checkout/updateCartItems": s81,
	"vtex/actions/checkout/updateCartItems.ts": s81,
	"vtex/actions/checkout/updateItemAttachment": s78,
	"vtex/actions/checkout/updateItemAttachment.ts": s78,
	"vtex/actions/checkout/updateItemPrice": s82,
	"vtex/actions/checkout/updateItemPrice.ts": s82,
	"vtex/actions/checkout/updateOrderFormAttachment": s83,
	"vtex/actions/checkout/updateOrderFormAttachment.ts": s83,
	"vtex/actions/checkout/updateOrderFormProfile": s84,
	"vtex/actions/checkout/updateOrderFormProfile.ts": s84,
	"vtex/actions/checkout/updateSelectableGifts": s85,
	"vtex/actions/checkout/updateSelectableGifts.ts": s85,
	"vtex/actions/masterData/createDocument": s86,
	"vtex/actions/masterData/createDocument.ts": s86,
	"vtex/actions/masterData/getDocument": s87,
	"vtex/actions/masterData/getDocument.ts": s87,
	"vtex/actions/masterData/patchDocument": s88,
	"vtex/actions/masterData/patchDocument.ts": s88,
	"vtex/actions/masterData/searchDocuments": s89,
	"vtex/actions/masterData/searchDocuments.ts": s89,
	"vtex/actions/masterData/searchDocumentsFull": s90,
	"vtex/actions/masterData/searchDocumentsFull.ts": s90,
	"vtex/actions/masterData/uploadAttachment": s91,
	"vtex/actions/masterData/uploadAttachment.ts": s91,
	"vtex/actions/misc/deletePaymentToken": s92,
	"vtex/actions/misc/deletePaymentToken.ts": s92,
	"vtex/actions/misc/notifyMe": s93,
	"vtex/actions/misc/notifyMe.ts": s93,
	"vtex/actions/misc/sendEvent": s94,
	"vtex/actions/misc/sendEvent.ts": s94,
	"vtex/actions/misc/submitReview": s95,
	"vtex/actions/misc/submitReview.ts": s95,
	"vtex/actions/newsletter/subscribe": s96,
	"vtex/actions/newsletter/subscribe.ts": s96,
	"vtex/actions/newsletter/updateNewsletterOptIn": s97,
	"vtex/actions/newsletter/updateNewsletterOptIn.ts": s97,
	"vtex/actions/orders/cancelOrder": s98,
	"vtex/actions/orders/cancelOrder.ts": s98,
	"vtex/actions/profile/deletePaymentFromRequest": s21,
	"vtex/actions/profile/deletePaymentFromRequest.ts": s21,
	"vtex/actions/profile/getPasswordLastUpdate": s21,
	"vtex/actions/profile/getPasswordLastUpdate.ts": s21,
	"vtex/actions/profile/newsletterProfileFromRequest": s21,
	"vtex/actions/profile/newsletterProfileFromRequest.ts": s21,
	"vtex/actions/profile/updateProfile": s99,
	"vtex/actions/profile/updateProfile.ts": s99,
	"vtex/actions/profile/updateProfileFromRequest": s100,
	"vtex/actions/profile/updateProfileFromRequest.ts": s100,
	"vtex/actions/session/createSession": s101,
	"vtex/actions/session/createSession.ts": s101,
	"vtex/actions/session/deleteSession": s102,
	"vtex/actions/session/deleteSession.ts": s102,
	"vtex/actions/session/editSession": s103,
	"vtex/actions/session/editSession.ts": s103,
	"vtex/actions/wishlist/addItem": s104,
	"vtex/actions/wishlist/addItem.ts": s104,
	"vtex/actions/wishlist/removeItem": s105,
	"vtex/actions/wishlist/removeItem.ts": s105,
};
